const shared = {
  updated: '2026-08-30',
  source: '个人学习笔记 · 原创整理'
};

function term(config) {
  return {
    ...shared,
    duration: config.level === '进阶' ? 11 : 8,
    userSays: config.userSays || config.excerpt,
    ...config
  };
}

export const expandedLessons = [
  term({
    id: 'html', title: 'HTML', english: 'HyperText Markup Language', aliases: ['超文本标记语言', '网页结构'], category: '前端航线', level: '入门',
    tags: ['HTML', '结构', '浏览器'], excerpt: '用标签描述网页内容的结构和含义。',
    definition: 'HTML 是描述网页结构的标记语言。它用元素告诉浏览器哪里是标题、段落、图片、表单和链接。',
    why: '浏览器先读取 HTML 建立页面骨架，CSS 再负责外观，JavaScript 再负责变化和行为。结构写错会影响可访问性、搜索和交互。',
    points: ['元素由标签、属性和内容组成', '文档结构要保持合法嵌套', '内容含义应优先于默认外观'],
    example: '文章标题使用 h1，正文使用 p，跳转到详情页使用带 href 的 a。',
    pitfalls: ['把 HTML 当成编程语言', '用 br 和空格硬凑布局', '只根据默认字号选择标题级别'],
    checklist: ['页面只有一个清晰主标题', '图片具有合适替代文本', '交互元素使用正确标签'],
    related: ['html-semantics', 'css', 'dom'],
    question: { prompt: 'HTML 在网页中主要负责什么？', choices: ['描述内容结构与含义', '连接数据库', '压缩图片'], answer: 0, explanation: 'HTML 建立内容骨架；视觉样式主要由 CSS 负责，业务数据通常由后端处理。' }
  }),
  term({
    id: 'css', title: 'CSS', english: 'Cascading Style Sheets', aliases: ['层叠样式表', '网页样式'], category: '前端航线', level: '入门',
    tags: ['CSS', '样式', '布局'], excerpt: '控制网页的颜色、排版、尺寸和响应式布局。',
    definition: 'CSS 是描述 HTML 如何呈现的样式语言，通过选择器找到元素，再应用颜色、间距、字体、布局和动画规则。',
    why: '把结构与视觉分开后，同一份内容可以适配不同屏幕和主题，也能用统一规则减少页面之间的视觉漂移。',
    points: ['层叠决定多条规则谁生效', '盒模型影响元素实际尺寸', 'Grid 与 Flexbox 负责常见布局'],
    example: '使用 CSS 变量统一操作色，并在窄屏断点把三列课程卡改成单列。',
    pitfalls: ['大量使用 !important 掩盖层叠问题', '用固定高度包住可变文字', '只在自己的屏幕尺寸调样式'],
    checklist: ['检查最终计算样式来源', '缩放和长文案下不溢出', '颜色对比度满足阅读要求'],
    related: ['html', 'responsive-layout', 'design-token'],
    question: { prompt: '按钮颜色一直被旧规则覆盖，先检查什么？', choices: ['CSS 选择器优先级与加载顺序', '数据库索引', 'API 状态码'], answer: 0, explanation: '层叠、优先级与声明顺序共同决定最终生效的 CSS。' }
  }),
  term({
    id: 'dom', title: '文档对象模型', english: 'Document Object Model', aliases: ['DOM', '页面节点树'], category: '前端航线', level: '入门',
    tags: ['DOM', '浏览器', '节点'], excerpt: '浏览器把 HTML 变成可读取和修改的对象树。',
    definition: 'DOM 是浏览器根据 HTML 建立的对象树，JavaScript 可以查询节点、修改内容、监听事件并更新界面。',
    why: '开发者工具里看到的当前 DOM 可能已经被脚本修改，与服务器最初返回的 HTML 不完全相同。',
    points: ['元素、文字和属性都是节点信息', '查询应尽量使用稳定选择器', '频繁大范围修改会增加渲染成本'],
    example: '新增任务后，脚本创建 li 并插入列表，因此运行时 DOM 出现新节点。',
    pitfalls: ['把源 HTML 当成页面最终状态', '使用脆弱的层级选择器', '反复重建整个页面导致焦点丢失'],
    checklist: ['在 Elements 面板确认真实节点', '动态内容保留可访问名称', '更新后焦点位置合理'],
    related: ['html', 'browser-event', 'component-thinking'],
    question: { prompt: '脚本新增内容后，源 HTML 中找不到它，应查看哪里？', choices: ['运行时 DOM', 'DNS 记录', 'Git 分支'], answer: 0, explanation: 'JavaScript 可以在页面加载后修改 DOM，源文件不会自动随运行时变化。' }
  }),
  term({
    id: 'browser-event', title: '浏览器事件', english: 'Browser Event', aliases: ['Event', '事件监听', '事件冒泡'], category: '前端航线', level: '进阶',
    tags: ['Event', '交互', '冒泡'], excerpt: '把点击、输入、提交和键盘操作连接到页面逻辑。',
    definition: '浏览器事件是用户或系统发生动作时产生的通知，例如 click、input、submit 和 keydown。代码通过监听器响应这些事件。',
    why: '理解事件目标、默认行为与冒泡路径，才能解释为什么一次点击触发多段代码，或为什么链接没有按预期跳转。',
    points: ['preventDefault 阻止浏览器默认动作', '事件会沿 DOM 路径冒泡', '事件委托适合动态列表'],
    example: '课程目录点击时阻止链接默认改写哈希，再调用 scrollIntoView 定位章节。',
    pitfalls: ['重复绑定同一个监听器', '阻止所有默认行为却不提供替代', '只监听鼠标而忽略键盘'],
    checklist: ['明确事件绑定位置', '交互兼容键盘与触控', '组件销毁时清理长期监听器'],
    related: ['dom', 'client-side-routing', 'accessibility'],
    question: { prompt: '点击子按钮同时触发父卡片点击，最可能与什么有关？', choices: ['事件冒泡', '数据库事务', 'DNS 缓存'], answer: 0, explanation: '点击事件会从目标元素沿祖先节点冒泡，需要根据职责处理传播。' }
  }),
  term({
    id: 'form-validation', title: '表单校验', english: 'Form Validation', aliases: ['Validation', '输入校验'], category: '前端航线', level: '入门',
    tags: ['表单', '校验', '错误提示'], excerpt: '在提交前后检查输入，并告诉用户如何修正。',
    definition: '表单校验检查必填、格式、长度和业务约束。前端校验改善反馈速度，后端校验负责真正守住数据边界。',
    why: '只做前端校验可以被绕过，只做后端校验又会让简单错误反馈太慢；两端职责不同但都需要。',
    points: ['错误信息紧邻对应字段', '提交后聚焦第一个错误', '服务端仍需重新验证全部输入'],
    example: '邮箱格式在输入结束后提示，注册接口再次验证邮箱、验证码和账号状态。',
    pitfalls: ['只用红框不写原因', '输入一个字符就显示全部错误', '相信浏览器传来的价格和权限'],
    checklist: ['错误说明包含修复方法', '无障碍技术能读到错误', '后端拒绝绕过前端的无效数据'],
    related: ['frontend', 'api-contract', 'error-handling'],
    question: { prompt: '前端已经校验邮箱，后端还需要再校验吗？', choices: ['需要，前端输入不可被信任', '不需要，会浪费性能', '只在手机端需要'], answer: 0, explanation: '前端校验用于体验，后端校验才是可信数据边界。' }
  }),
  term({
    id: 'async-request', title: '异步请求', english: 'Asynchronous Request', aliases: ['Fetch', 'Ajax', '网络请求'], category: '前端航线', level: '进阶',
    tags: ['Fetch', '异步', '请求'], excerpt: '页面不整体刷新，也能向服务端读取或提交数据。',
    definition: '异步请求允许页面在等待网络结果时继续响应操作，结果返回后再更新对应界面状态。',
    why: '网络速度和结果都不确定，因此必须显式处理等待、成功、失败、取消和过期响应。',
    points: ['请求开始时呈现 pending 状态', '只把真实成功结果显示为成功', '旧请求结果不应覆盖新选择'],
    example: '用户搜索时发出请求；新的关键词出现后取消旧请求，避免旧结果最后返回并覆盖页面。',
    pitfalls: ['忘记 await 就直接读取结果', '只处理成功路径', '快速点击产生重复写入'],
    checklist: ['加载状态不会阻塞无关操作', '错误可以重试', '重复提交有防护'],
    related: ['api-contract', 'state-management', 'error-handling'],
    question: { prompt: '请求还没返回就显示“保存成功”，问题是什么？', choices: ['把等待状态误当成成功状态', 'CSS 文件过大', 'HTML 不语义化'], answer: 0, explanation: '异步操作的结果尚未确定，应保持等待状态直到收到可信响应。' }
  }),
  term({
    id: 'client-side-routing', title: '前端路由', english: 'Client-side Routing', aliases: ['SPA Router', '客户端路由', 'Hash Router'], category: '前端航线', level: '进阶',
    tags: ['路由', 'SPA', 'URL'], excerpt: '让单页应用用地址表示不同页面和状态。',
    definition: '前端路由监听 URL 变化，在不整页重新加载的情况下选择要渲染的页面。',
    why: '正确路由让前进、后退、刷新和分享链接都可用；页内锚点与应用路由还需要避免冲突。',
    points: ['每个主要页面应有稳定地址', '未知路由需要 404 状态', '页面切换后管理滚动与焦点'],
    example: '知识详情使用 #/lesson/frontend，目录滚动通过事件处理，不把 #definition 交给全局路由。',
    pitfalls: ['只改页面不更新地址', '刷新深层地址返回服务器 404', '路由变化后焦点仍留在旧内容'],
    checklist: ['浏览器返回键行为正确', '复制地址可以恢复当前页', '锚点与路由规则不冲突'],
    related: ['browser-event', 'information-architecture', 'frontend'],
    question: { prompt: '单页应用切换详情后，刷新回到首页，首先检查什么？', choices: ['路由地址和服务器回退配置', '按钮圆角', '数据库字段长度'], answer: 0, explanation: '客户端路由必须有可恢复的 URL，服务器也要把深层地址交回应用入口。' }
  }),
  term({
    id: 'browser-storage', title: '浏览器存储', english: 'Browser Storage', aliases: ['localStorage', 'sessionStorage', '客户端存储'], category: '前端航线', level: '入门',
    tags: ['localStorage', '缓存', '本地数据'], excerpt: '在当前浏览器保存偏好、草稿和轻量状态。',
    definition: '浏览器存储是在用户设备上保存数据的机制，常见有 localStorage、sessionStorage 和 IndexedDB。',
    why: '它适合主题、草稿和离线状态，但不是跨用户共享数据库，清理浏览器数据后也可能消失。',
    points: ['localStorage 只保存字符串', '敏感信息不应直接长期保存', '读取时要处理缺失和损坏数据'],
    example: '个人学习站把收藏 ID 和笔记保存在本地，让刷新后继续存在。',
    pitfalls: ['把令牌和秘密明文存放', '假设所有设备自动同步', 'JSON 解析失败导致整页崩溃'],
    checklist: ['存储用途与生命周期清楚', '提供默认值和迁移策略', '不保存不必要的个人数据'],
    related: ['state-management', 'database', 'frontend'],
    question: { prompt: '笔记需要在手机和电脑登录后同步，localStorage 足够吗？', choices: ['不够，需要后端账号与持久化存储', '足够，会自动同步', '只要改成 sessionStorage'], answer: 0, explanation: '浏览器存储通常只属于当前浏览器环境，跨设备同步需要服务端数据。' }
  }),
  term({
    id: 'css-flexbox', title: 'Flexbox', english: 'Flexible Box Layout', aliases: ['弹性布局', 'Flex 布局'], category: '前端航线', level: '入门',
    tags: ['CSS', 'Flexbox', '布局'], excerpt: '沿一个主轴排列、对齐和分配界面元素。',
    definition: 'Flexbox 是一维布局系统，擅长处理一行或一列中的对齐、间距、伸缩和顺序。',
    why: '导航栏、按钮组和左右对齐区域使用 Flexbox 往往比浮动或手写边距更稳定。',
    points: ['主轴由 flex-direction 决定', 'justify-content 控制主轴分布', 'align-items 控制交叉轴对齐'],
    example: '顶栏用 display:flex，让搜索框占剩余空间，状态信息保持在右侧。',
    pitfalls: ['把二维网格强行塞进 Flexbox', '忘记子项默认允许收缩', '依赖 order 改变视觉顺序却不改阅读顺序'],
    checklist: ['长文字时布局仍可换行', '键盘顺序与视觉顺序一致', '需要二维布局时考虑 Grid'],
    related: ['css', 'responsive-layout', 'css-grid'],
    question: { prompt: '同一行中左侧标题、右侧按钮最直接的布局方式是？', choices: ['Flexbox 配合两端对齐', '连续输入空格', '给按钮固定 left 值'], answer: 0, explanation: 'Flexbox 能根据可用宽度稳定分配并对齐一维内容。' }
  }),
  term({
    id: 'css-grid', title: 'CSS Grid', english: 'CSS Grid Layout', aliases: ['网格布局', 'Grid'], category: '前端航线', level: '进阶',
    tags: ['CSS', 'Grid', '布局'], excerpt: '用行和列共同组织二维页面结构。',
    definition: 'CSS Grid 是二维布局系统，可以同时定义列、行、间距和区域，适合页面框架与规则卡片网格。',
    why: '当内容需要横纵同时对齐时，Grid 比嵌套多层 Flexbox 更能直接表达布局关系。',
    points: ['fr 分配剩余空间', 'minmax 保护最小宽度', 'auto-fit 可生成自适应列数'],
    example: '课程索引使用 repeat(3,minmax(0,1fr))，在断点下降为两列和一列。',
    pitfalls: ['把所有元素固定到绝对网格线', '窄屏仍强制多列', '忽略内容最小宽度造成溢出'],
    checklist: ['列宽由内容和空间共同决定', '断点下阅读顺序自然', '不依赖空元素占位'],
    related: ['css', 'responsive-layout', 'css-flexbox'],
    question: { prompt: '需要三列卡片并在窄屏自动减少列数，适合使用什么？', choices: ['CSS Grid', 'HTML table 强行布局', '绝对定位'], answer: 0, explanation: 'Grid 能直接表达响应式列结构，并保持卡片在文档流中。' }
  }),
  term({
    id: 'backend', title: '后端', english: 'Backend', aliases: ['服务端', 'Server-side'], category: '后端航线', level: '入门',
    tags: ['服务端', '业务规则', '数据'], excerpt: '在浏览器之外处理可信规则、请求和持久化数据。',
    definition: '后端是运行在用户无法直接控制的环境中，负责接收请求、验证身份、执行规则、读写数据并返回结果的系统部分。',
    why: '密码校验、真实价格和权限判断必须由可信环境完成，不能只依赖用户可以修改的前端代码。',
    points: ['接收并验证外部输入', '执行权限与业务规则', '协调数据库和外部服务'],
    example: '注册接口检查验证码和手机号是否占用，创建账号后返回安全的用户信息。',
    pitfalls: ['把后端等同于一台物理服务器', '把数据库错误直接发给用户', '相信前端传来的身份与价格'],
    checklist: ['所有输入都经过验证', '权限在服务端重新判断', '日志不记录密码和密钥'],
    related: ['frontend', 'api', 'database'],
    question: { prompt: '商品最终成交价格应该由哪里确认？', choices: ['后端根据可信规则计算', '前端隐藏输入框', '用户浏览器缓存'], answer: 0, explanation: '前端数据可被修改，涉及资金和权限的规则必须在后端确认。' }
  }),
  term({
    id: 'http', title: 'HTTP', english: 'Hypertext Transfer Protocol', aliases: ['超文本传输协议', '请求响应'], category: '后端航线', level: '入门',
    tags: ['HTTP', '请求', '响应'], excerpt: '浏览器与服务器交换请求和响应的通用规则。',
    definition: 'HTTP 定义客户端如何发送方法、地址、头和内容，以及服务器如何返回状态码、头和响应体。',
    why: '理解一次请求的完整信息，才能区分地址错误、权限失败、服务器异常和浏览器展示问题。',
    points: ['方法表达操作意图', '状态码概括处理结果', '请求头携带格式与身份信息'],
    example: 'GET /api/lessons 读取列表，服务器返回 200 与 JSON；未登录可能返回 401。',
    pitfalls: ['所有操作都使用 GET', '忽略状态码只看文字', '把 HTTP 与互联网本身混为一谈'],
    checklist: ['方法和资源语义一致', '状态码与响应体不矛盾', '敏感通信使用 HTTPS'],
    related: ['api', 'route-endpoint', 'authentication'],
    question: { prompt: '服务器返回 404 通常表示什么？', choices: ['请求的资源或路由未找到', '请求一定成功', '浏览器没有 CSS'], answer: 0, explanation: '404 表示服务器未找到与请求地址匹配的资源。' }
  }),
  term({
    id: 'api', title: 'API', english: 'Application Programming Interface', aliases: ['应用程序接口', '接口'], category: '后端航线', level: '入门',
    tags: ['API', '接口', '集成'], excerpt: '让不同程序通过明确入口和格式交换能力与数据。',
    definition: 'API 是一个系统向其他程序公开的可调用能力，Web API 通常通过 HTTP 地址接收参数并返回结构化结果。',
    why: 'API 把调用方与内部实现隔开，前端只需遵守约定，不必知道数据具体存在哪张表。',
    points: ['入口、输入和输出必须明确', '认证和调用限制属于接口规则', '版本变化要考虑兼容性'],
    example: '天气 API 接收城市代码，返回温度、天气状态和更新时间。',
    pitfalls: ['把 API 当成数据库', '没有错误示例', '在前端暴露私密 API Key'],
    checklist: ['阅读官方接口文档', '处理超时和限流', '验证返回字段再使用'],
    related: ['api-contract', 'http', 'json'],
    question: { prompt: 'API 最核心的价值是什么？', choices: ['提供程序之间稳定的调用约定', '自动设计所有页面', '替代版本控制'], answer: 0, explanation: 'API 用明确契约暴露数据或能力，使系统可以独立演进和协作。' }
  }),
  term({
    id: 'rest-api', title: 'REST API', english: 'Representational State Transfer API', aliases: ['RESTful', '资源接口'], category: '后端航线', level: '进阶',
    tags: ['REST', 'API', '资源'], excerpt: '围绕资源和 HTTP 语义组织常见接口。',
    definition: 'REST 风格 API 通常用 URL 表示资源，用 HTTP 方法表示读取、创建、修改和删除等操作。',
    why: '一致的资源命名和方法语义能降低接口学习成本，但 REST 是设计风格，不是必须照抄的固定公式。',
    points: ['资源名通常使用名词', 'GET 应保持只读', '响应应使用有意义的状态码'],
    example: 'GET /posts 读取列表，POST /posts 创建文章，PATCH /posts/42 更新文章。',
    pitfalls: ['把动作都塞进 /api/do', '用 GET 修改数据', '为了形式强行拆出难懂资源'],
    checklist: ['路径命名一致', '方法语义可预测', '分页与错误格式明确'],
    related: ['api', 'route-endpoint', 'crud'],
    question: { prompt: '创建一篇新文章通常使用哪种组合？', choices: ['POST /posts', 'GET /posts/create-now', 'DELETE /posts'], answer: 0, explanation: 'REST 风格通常用 POST 向集合资源创建新条目。' }
  }),
  term({
    id: 'route-endpoint', title: '路由与端点', english: 'Route & Endpoint', aliases: ['Route', 'Endpoint', '接口路由'], category: '后端航线', level: '入门',
    tags: ['路由', '端点', 'HTTP'], excerpt: '把请求的方法和路径交给对应的处理代码。',
    definition: '后端路由根据 HTTP 方法与路径匹配处理函数；一个可调用的具体入口通常称为端点。',
    why: '只有路径相同还不够，GET 与 POST 可以进入完全不同的逻辑，参数、身份和响应也各有约定。',
    points: ['方法与路径共同确定入口', '路径参数标识具体资源', '处理函数应保持职责聚焦'],
    example: 'GET /api/posts/:id 进入文章详情处理函数，POST /api/posts 进入创建函数。',
    pitfalls: ['一个端点承担所有业务', '相同操作使用多种路径命名', '路由存在却没有权限检查'],
    checklist: ['列出方法、路径和参数', '验证不存在资源的结果', '确认未授权请求被拒绝'],
    related: ['http', 'api-contract', 'backend'],
    question: { prompt: 'GET /posts 和 POST /posts 是否是同一个端点行为？', choices: ['不是，方法不同对应不同操作', '是，只看路径', '只在手机端不同'], answer: 0, explanation: 'HTTP 方法与路径共同构成请求匹配条件。' }
  }),
  term({
    id: 'json', title: 'JSON', english: 'JavaScript Object Notation', aliases: ['结构化数据', 'JSON 数据'], category: '后端航线', level: '入门',
    tags: ['JSON', '数据格式', 'API'], excerpt: '用对象、数组和基本值交换结构化数据。',
    definition: 'JSON 是常见文本数据格式，支持对象、数组、字符串、数字、布尔值和 null，经常作为 Web API 请求体与响应体。',
    why: '它便于人阅读和程序解析，但只负责表示数据，不会自动验证字段含义或执行函数。',
    points: ['属性名和字符串使用双引号', '不支持注释与 undefined', '解析外部 JSON 仍要校验结构'],
    example: '课程接口返回 {"id":"html","completed":false}，前端据此渲染状态。',
    pitfalls: ['把 JavaScript 对象语法全部当 JSON', '信任解析后的所有字段', '手工拼接 JSON 造成转义错误'],
    checklist: ['Content-Type 标明 application/json', '解析失败有处理', '字段类型经过验证'],
    related: ['api', 'api-contract', 'data-model'],
    question: { prompt: '下面哪项不是标准 JSON 支持的值？', choices: ['函数', '字符串', '布尔值'], answer: 0, explanation: 'JSON 表示数据，不支持函数、注释或 undefined。' }
  }),
  term({
    id: 'database', title: '数据库', english: 'Database', aliases: ['DB', '持久化存储'], category: '后端航线', level: '入门',
    tags: ['数据库', '持久化', '查询'], excerpt: '长期保存并可靠查询用户、内容和业务记录。',
    definition: '数据库是有组织地保存、查询和更新应用数据的系统，通常由后端访问并执行约束。',
    why: '浏览器刷新后仍存在、跨设备共享并需要权限控制的数据，通常要进入服务端持久化存储。',
    points: ['表或集合组织相关记录', '索引提高常用查询速度', '约束保护数据一致性'],
    example: '用户完成课程后，后端把 user_id、lesson_id 和 completed_at 写入学习记录表。',
    pitfalls: ['把大文件全部塞进普通字段', '没有备份和恢复验证', '让前端直接连接生产数据库'],
    checklist: ['数据归属与权限明确', '关键字段有约束', '备份能够实际恢复'],
    related: ['data-model', 'sql', 'browser-storage'],
    question: { prompt: '内容需要登录后在多台设备读取，应该保存在哪里？', choices: ['由后端写入数据库', '只放页面变量', '只放 sessionStorage'], answer: 0, explanation: '跨设备持久化需要服务端可访问并受权限保护的数据存储。' }
  }),
  term({
    id: 'sql', title: 'SQL', english: 'Structured Query Language', aliases: ['结构化查询语言', '数据库查询'], category: '后端航线', level: '进阶',
    tags: ['SQL', '数据库', '查询'], excerpt: '声明要读取或修改哪些关系型数据。',
    definition: 'SQL 是操作关系型数据库的语言，可用于查询、插入、更新、删除数据以及定义表和约束。',
    why: 'SQL 描述想得到的结果，由数据库选择执行方式；正确参数化和索引设计决定安全性与效率。',
    points: ['SELECT 读取数据', 'WHERE 限定目标记录', '参数化查询防止注入'],
    example: 'SELECT title FROM lessons WHERE level = ? 使用参数传入难度，而不是拼接用户输入。',
    pitfalls: ['遗漏 WHERE 更新整张表', '拼接用户输入形成 SQL 注入', '用 SELECT * 读取不需要的大字段'],
    checklist: ['写操作先确认影响范围', '动态值全部参数化', '慢查询查看执行计划'],
    related: ['database', 'crud', 'data-model'],
    question: { prompt: '避免 SQL 注入最基本的做法是什么？', choices: ['使用参数化查询', '把输入转成红色', '增加页面加载动画'], answer: 0, explanation: '参数化让数据不会被当成 SQL 代码结构执行。' }
  }),
  term({
    id: 'crud', title: 'CRUD', english: 'Create Read Update Delete', aliases: ['增删改查', '数据操作'], category: '后端航线', level: '入门',
    tags: ['CRUD', 'API', '数据库'], excerpt: '创建、读取、更新和删除数据的四类基本操作。',
    definition: 'CRUD 是 Create、Read、Update、Delete 的缩写，用来概括应用对持久化数据最常见的操作。',
    why: '用 CRUD 梳理资源生命周期，可以发现缺失的权限、确认、撤销和错误处理。',
    points: ['创建需要校验和唯一性处理', '更新要确认目标与版本', '删除应区分软删除和永久删除'],
    example: '笔记可以新建、读取、编辑和删除，每一步都只能操作当前用户的数据。',
    pitfalls: ['把 CRUD 当成完整业务设计', '删除没有确认或恢复方案', '更新时覆盖并发修改'],
    checklist: ['每类操作定义权限', '失败结果清楚', '危险删除具有保护'],
    related: ['rest-api', 'database', 'authorization'],
    question: { prompt: 'CRUD 中的 U 表示什么？', choices: ['Update 更新', 'Upload 上传', 'User 用户'], answer: 0, explanation: 'CRUD 依次是创建、读取、更新与删除。' }
  }),
  term({
    id: 'authentication', title: '身份认证', english: 'Authentication', aliases: ['AuthN', '登录', '身份验证'], category: '后端航线', level: '进阶',
    tags: ['认证', '登录', '会话'], excerpt: '确认当前请求者是谁。',
    definition: '身份认证验证用户身份，常见方式包括密码、短信验证码、Passkey 和第三方登录。',
    why: '认证回答“你是谁”，成功后通常建立会话或发放令牌；它不自动代表用户能执行所有操作。',
    points: ['密码使用安全哈希而非可逆保存', '会话需要过期和撤销机制', '高风险操作可要求再次验证'],
    example: '用户登录后获得安全会话 Cookie，后续请求由后端据此识别用户。',
    pitfalls: ['在日志中记录密码', '只在前端保存 isLoggedIn', '会话永久不过期'],
    checklist: ['失败信息不泄露账号是否存在', 'Cookie 使用合适安全属性', '退出登录能使会话失效'],
    related: ['authorization', 'http', 'backend'],
    question: { prompt: '身份认证主要回答哪个问题？', choices: ['你是谁', '你能做什么', '页面是什么颜色'], answer: 0, explanation: '认证识别主体；能做什么属于授权。' }
  }),
  term({
    id: 'authorization', title: '权限授权', english: 'Authorization', aliases: ['AuthZ', '权限控制', '访问控制'], category: '后端航线', level: '进阶',
    tags: ['授权', '权限', '安全'], excerpt: '判断已识别的用户能否执行这次操作。',
    definition: '权限授权根据用户、角色、资源归属和操作判断是否允许访问，是认证之后的独立步骤。',
    why: '登录成功不代表可以查看所有人的订单或修改管理员设置，每个敏感操作都必须在后端检查权限。',
    points: ['默认拒绝未明确允许的操作', '检查具体资源归属', '前端隐藏按钮只是体验优化'],
    example: '编辑笔记时，后端同时核对当前用户 ID 与笔记 owner_id。',
    pitfalls: ['只按页面入口控制权限', '用用户传来的 ownerId 做判断', '管理员接口没有独立保护'],
    checklist: ['横向越权测试', '未登录与无权限结果区分', '权限变化及时生效'],
    related: ['authentication', 'crud', 'api-contract'],
    question: { prompt: '用户已登录但访问了别人的私密笔记，应检查什么？', choices: ['资源级授权', '字体加载', '页面动画'], answer: 0, explanation: '认证只确认身份，还必须判断该身份是否有权访问具体资源。' }
  }),
  term({
    id: 'environment-variable', title: '环境变量', english: 'Environment Variable', aliases: ['Env Var', '.env', '运行配置'], category: '后端航线', level: '入门',
    tags: ['配置', '密钥', '环境'], excerpt: '把随运行环境变化的配置与代码分离。',
    definition: '环境变量是在程序运行时由系统注入的配置，例如数据库地址、部署模式和第三方服务密钥。',
    why: '开发、测试和生产环境的配置不同；将密钥写进代码会进入版本历史并可能泄露。',
    points: ['变量名保持稳定', '启动时校验必需配置', '前端公开变量不能保存秘密'],
    example: '后端从 DATABASE_URL 读取数据库连接，而 .env 文件被 .gitignore 排除。',
    pitfalls: ['把 .env 提交到仓库', '变量缺失时静默使用危险默认值', '把服务端密钥注入浏览器构建'],
    checklist: ['示例文件只列名称不含秘密', '生产密钥使用安全托管', '泄露后立即轮换'],
    related: ['backend', 'gitignore', 'deployment'],
    question: { prompt: 'API 密钥最不应该放在哪里？', choices: ['提交进前端源代码', '服务端安全环境变量', '部署平台的秘密配置'], answer: 0, explanation: '前端代码和版本历史都可能被访问，不能保存可信密钥。' }
  }),
  term({
    id: 'token', title: 'Token', english: 'AI Token', aliases: ['词元', '模型计数单位'], category: 'AI 协作', level: '入门',
    tags: ['Token', '模型', '成本'], excerpt: '模型读取和生成文本时使用的基本计数单位。',
    definition: 'Token 是模型处理文本时切分出的片段，可能是一个字、词的一部分或标点，并不等同于字符数。',
    why: '输入和输出 Token 会占用上下文容量，也常用于计算调用成本和限制响应长度。',
    points: ['不同模型的切分方式可能不同', '中文字符与 Token 不是固定一比一', '代码与结构化数据也会消耗 Token'],
    example: '把重复日志全部粘贴会占满上下文，先保留关键错误、调用栈和复现步骤更有效。',
    pitfalls: ['把 Token 当登录令牌', '只压缩字数却丢失关键条件', '忽略长工具输出的占用'],
    checklist: ['保留影响判断的证据', '移除重复上下文', '长任务分阶段总结状态'],
    related: ['context-window', 'prompt-context', 'system-prompt'],
    question: { prompt: '减少 AI 上下文占用最合理的方式是？', choices: ['删掉重复内容并保留关键证据', '删除所有错误信息', '把同一句话重复三遍'], answer: 0, explanation: '目标是提高信息密度，而不是盲目缩短导致关键上下文缺失。' }
  }),
  term({
    id: 'context-window', title: '上下文窗口', english: 'Context Window', aliases: ['上下文长度', 'Context Length'], category: 'AI 协作', level: '进阶',
    tags: ['上下文', 'Token', '模型'], excerpt: '模型一次能够共同参考的输入与输出容量。',
    definition: '上下文窗口是模型在一次任务中可处理的 Token 总容量，包含指令、对话、文件内容、工具结果和生成内容。',
    why: '内容超过窗口后，早期信息可能被截断或压缩；即使没有超限，过多噪声也会降低模型定位重点的能力。',
    points: ['上下文容量不是长期记忆', '相关性比单纯长度更重要', '大型任务需要持续状态摘要'],
    example: '代码修复只加载相关组件、测试和错误日志，不把整个仓库无差别塞入。',
    pitfalls: ['假设模型永远记住所有早期细节', '一次提供大量无关文件', '压缩摘要时漏掉未完成事项'],
    checklist: ['关键约束在当前上下文可见', '工具输出按需截取', '长任务维护完成与待办清单'],
    related: ['token', 'prompt-context', 'iteration-loop'],
    question: { prompt: '上下文越长，结果是否一定越好？', choices: ['不一定，噪声会稀释关键信息', '一定', '只对图片一定'], answer: 0, explanation: '足够且相关的上下文最有价值，无关内容会增加定位难度。' }
  }),
  term({
    id: 'hallucination', title: '模型幻觉', english: 'Hallucination', aliases: ['AI 幻觉', '虚构事实'], category: 'AI 协作', level: '入门',
    tags: ['幻觉', '事实核查', '不确定性'], excerpt: '模型生成看似合理但缺少事实依据的内容。',
    definition: '模型幻觉指输出语气确定，却包含不存在的事实、链接、接口、文件或错误推断。',
    why: '语言流畅不等于事实正确。涉及版本、价格、法律、医学或具体代码库状态时，需要使用可靠来源和实际运行验证。',
    points: ['要求区分事实与推断', '引用应能直接打开核验', '代码必须在真实环境执行'],
    example: 'Agent 声称某函数存在时，先在仓库搜索定义和调用，而不是直接按描述修改。',
    pitfalls: ['把自信语气当证据', '引用无法访问的虚构页面', '发现不确定仍继续编造细节'],
    checklist: ['关键事实有来源', '结论能被独立复现', '不确定之处明确标记'],
    related: ['acceptance-criteria', 'tool-calling', 'iteration-loop'],
    question: { prompt: 'AI 说某配置已经生效，最可靠的下一步是？', choices: ['在真实环境检查配置和行为', '相信语气很确定', '让它再说一次'], answer: 0, explanation: '可观察证据比语言置信度更可靠。' }
  }),
  term({
    id: 'rag', title: '检索增强生成', english: 'Retrieval-Augmented Generation', aliases: ['RAG', '知识库问答'], category: 'AI 协作', level: '进阶',
    tags: ['RAG', '检索', '知识库'], excerpt: '先检索相关资料，再让模型基于资料生成回答。',
    definition: 'RAG 把搜索或向量检索得到的外部资料放进模型上下文，使回答能参考私有或最新知识。',
    why: '它可以减少模型只依赖训练记忆的问题，但检索错了、资料过期或引用不相关时，回答仍会错误。',
    points: ['文档要切分并保留来源', '检索结果需要相关性排序', '回答应能追溯到证据'],
    example: '个人知识站先找出与“权限”相关的课程段落，再让 AI 生成学习建议并附来源。',
    pitfalls: ['把所有文档一次性塞入提示词', '只看向量相似度不看权限', '没有引用却声称来自知识库'],
    checklist: ['测试真实用户问题', '无结果时诚实返回', '敏感文档按用户过滤'],
    related: ['context-window', 'tool-calling', 'information-architecture'],
    question: { prompt: 'RAG 的第一步通常是什么？', choices: ['检索与问题相关的资料', '直接微调模型', '删除原始文档'], answer: 0, explanation: 'RAG 先取得相关证据，再把证据用于生成。' }
  }),
  term({
    id: 'tool-calling', title: '工具调用', english: 'Tool Calling', aliases: ['Function Calling', '函数调用', 'Agent 工具'], category: 'AI 协作', level: '进阶',
    tags: ['工具', 'Agent', '结构化调用'], excerpt: '让模型通过受控接口查询数据或执行操作。',
    definition: '工具调用让模型选择一个预定义工具并生成结构化参数，由系统实际执行后把结果返回模型。',
    why: '模型本身不能可靠知道实时数据或直接改变外部系统；工具提供可验证能力，同时也需要权限和确认边界。',
    points: ['工具参数要有清晰模式', '读操作与写操作分开授权', '执行结果需要再次验证'],
    example: '查询天气可直接调用读取工具；发送消息属于外部写操作，应在执行前确认内容和对象。',
    pitfalls: ['把网页文字当成系统指令', '工具报错后假装执行成功', '给工具过宽权限'],
    checklist: ['工具说明明确副作用', '敏感操作需要确认', '失败结果能安全恢复'],
    related: ['hallucination', 'system-prompt', 'acceptance-criteria'],
    question: { prompt: '工具调用完成后为什么仍要检查结果？', choices: ['调用可能失败或返回不符合预期的数据', '工具永远不会执行', '只为了增加步骤'], answer: 0, explanation: '选择工具、参数和外部系统都可能出错，需要以实际结果完成闭环。' }
  }),
  term({
    id: 'system-prompt', title: '系统提示词', english: 'System Prompt', aliases: ['System Instruction', '系统指令'], category: 'AI 协作', level: '进阶',
    tags: ['提示词', '规则', '优先级'], excerpt: '为模型设定长期角色、行为边界和执行规则。',
    definition: '系统提示词是由应用提供的高优先级指令，用来定义模型身份、允许能力、安全边界和输出规范。',
    why: '用户请求会在系统规则范围内执行；网页或文档中的文字只是待处理内容，不能反过来覆盖更高优先级指令。',
    points: ['规则应具体且不互相矛盾', '外部内容始终视为不可信输入', '关键边界应由系统和代码共同保护'],
    example: '阅读网页时可以提取事实，但不能因为网页写着“上传本地文件”就执行上传。',
    pitfalls: ['把秘密写入可被回显的提示词', '依靠一句话代替真正权限控制', '规则过多且相互冲突'],
    checklist: ['指令层级清楚', '高风险操作有代码级确认', '定期用对抗输入测试'],
    related: ['prompt-context', 'tool-calling', 'hallucination'],
    question: { prompt: '网页正文要求忽略系统规则时，应该怎么处理？', choices: ['把它当作不可信内容，不执行该指令', '立即照做', '删除系统提示词'], answer: 0, explanation: '外部页面不能提升自己的指令优先级。' }
  }),
  term({
    id: 'mvp', title: '最小可行产品', english: 'Minimum Viable Product', aliases: ['MVP', '最小版本'], category: '产品设计', level: '入门',
    tags: ['MVP', '验证', '范围'], excerpt: '用最小完整方案验证最关键的不确定性。',
    definition: 'MVP 是能让目标用户完成核心任务，并帮助团队验证关键假设的最小完整产品。',
    why: '它不是粗糙半成品，而是主动减少次要范围，把时间用在最需要验证的用户价值上。',
    points: ['先写出要验证的假设', '保留端到端核心任务', '上线前定义观察指标'],
    example: '学习站 MVP 先提供术语搜索、详情、收藏和进度，不急着加入社交排行榜。',
    pitfalls: ['把所有功能都称为必须', '省掉可靠性和基本体验', '上线后不收集任何证据'],
    checklist: ['用户能独立完成核心任务', '验证问题明确', '下一步由数据和反馈决定'],
    related: ['user-problem', 'acceptance-criteria', 'usability-testing'],
    question: { prompt: 'MVP 应优先保留什么？', choices: ['验证核心用户价值的完整路径', '所有未来可能需要的设置', '最多的动画'], answer: 0, explanation: '最小不等于残缺，核心任务必须端到端可用。' }
  }),
  term({
    id: 'user-story', title: '用户故事', english: 'User Story', aliases: ['需求故事', 'As a user'], category: '产品设计', level: '入门',
    tags: ['用户故事', '需求', '价值'], excerpt: '用角色、目标和价值表达一项需求。',
    definition: '用户故事通常描述“作为某类用户，我想完成某个目标，从而获得某种价值”，用来保持需求与用户任务连接。',
    why: '它帮助团队讨论为什么做，但不能替代详细验收标准、交互边界和研究证据。',
    points: ['角色要具体且有差异', '目标描述结果而非控件', '价值解释为什么值得做'],
    example: '作为刚入门的开发者，我想收藏术语，以便下次快速回到正在理解的概念。',
    pitfalls: ['把技术任务硬套成用户故事', '角色永远写成“用户”', '没有验收标准就直接开发'],
    checklist: ['故事能引出真实对话', '不提前锁定界面形式', '配套可验证标准'],
    related: ['user-problem', 'acceptance-criteria', 'user-flow'],
    question: { prompt: '用户故事中的“从而”部分主要表达什么？', choices: ['用户获得的价值', '数据库表名', '按钮颜色'], answer: 0, explanation: '价值说明用户为什么需要完成这个目标。' }
  }),
  term({
    id: 'user-flow', title: '用户流程', english: 'User Flow', aliases: ['任务流程', '用户路径'], category: '产品设计', level: '入门',
    tags: ['流程', '路径', '交互'], excerpt: '描述用户从起点到完成任务所经过的页面和决策。',
    definition: '用户流程把目标拆成一连串页面、操作、系统反馈和分支，用于检查任务是否完整。',
    why: '只设计单个漂亮页面容易遗漏等待、失败、返回和取消等真实状态。',
    points: ['起点与成功条件明确', '分支包含失败与恢复', '每一步只要求必要信息'],
    example: '搜索术语—打开详情—完成选择题—记录笔记—标记学完，构成一条学习流程。',
    pitfalls: ['只画理想成功路径', '流程节点使用模糊名称', '让用户来回重复输入'],
    checklist: ['所有分支都有出口', '关键反馈紧跟操作', '返回后保留必要状态'],
    related: ['information-architecture', 'wireframe', 'error-handling'],
    question: { prompt: '用户流程图最容易帮助发现什么？', choices: ['缺失的状态与恢复路径', '最终字体文件大小', '数据库密码'], answer: 0, explanation: '把步骤和分支展开后，等待、失败、取消等遗漏会更明显。' }
  }),
  term({
    id: 'wireframe', title: '线框图', english: 'Wireframe', aliases: ['低保真原型', '页面草图'], category: '产品设计', level: '入门',
    tags: ['线框图', '原型', '布局'], excerpt: '用低成本草图确认信息层级和任务路径。',
    definition: '线框图用简化方框、文字和连接关系表达页面结构、内容优先级与操作位置，通常不讨论最终视觉细节。',
    why: '在颜色和插画之前暴露结构问题，修改成本更低，也能让讨论聚焦用户任务。',
    points: ['真实文案长度比灰色占位更可靠', '标出关键状态与跳转', '移动端需要单独验证结构'],
    example: '先画课程详情的标题、目录、正文、练习和笔记顺序，再进入深色视觉设计。',
    pitfalls: ['把线框图当最终设计', '全部使用 lorem ipsum', '只画首页不画交互结果'],
    checklist: ['核心操作位置明显', '信息层级能口头解释', '关键流程可以连续走通'],
    related: ['user-flow', 'information-architecture', 'design-token'],
    question: { prompt: '线框图阶段应优先确认什么？', choices: ['信息结构和任务路径', '最终阴影像素', '品牌插画细节'], answer: 0, explanation: '线框图的价值是低成本验证结构，而不是提前完成视觉润色。' }
  }),
  term({
    id: 'usability-testing', title: '可用性测试', english: 'Usability Testing', aliases: ['用户测试', '任务测试'], category: '产品设计', level: '进阶',
    tags: ['可用性', '研究', '测试'], excerpt: '观察真实用户完成任务，而不是询问他们是否喜欢。',
    definition: '可用性测试让目标用户尝试具体任务，研究者观察他们在哪里犹豫、误解、失败或绕路。',
    why: '用户说“看起来不错”并不能证明能完成任务；行为证据能直接暴露导航、文案和反馈问题。',
    points: ['给任务目标，不教操作步骤', '主持人保持中立', '记录行为与原话而非替用户解释'],
    example: '请参与者找到“API 契约”、收藏并完成练习，观察他是否理解分类和按钮反馈。',
    pitfalls: ['测试时不断提示正确答案', '只邀请项目成员', '一次发现就直接推断所有用户'],
    checklist: ['任务贴近真实场景', '问题按严重度归类', '修复后重复验证关键路径'],
    related: ['user-interview', 'mvp', 'iteration-loop'],
    question: { prompt: '可用性测试中主持人应该怎么做？', choices: ['观察并用中立问题追问', '看到犹豫就立刻教学', '努力说服用户喜欢方案'], answer: 0, explanation: '过早帮助会掩盖真实问题，中立观察才能获得有效证据。' }
  }),
  term({
    id: 'git', title: 'Git', english: 'Git Version Control', aliases: ['版本控制', '源码管理'], category: '工程实践', level: '入门',
    tags: ['Git', '版本', '历史'], excerpt: '记录代码变化，让比较、协作和恢复成为可靠流程。',
    definition: 'Git 是分布式版本控制系统，用提交记录项目快照，并支持分支、合并、比较和恢复。',
    why: 'Git 保存在本地的完整历史；GitHub 等平台用于托管远程仓库与协作，两者不是同一件事。',
    points: ['工作区保存当前文件变化', '暂存区选择下次提交内容', '提交进入本地历史'],
    example: '大型改动前先检查状态、运行测试并建立清晰提交，形成可恢复点。',
    pitfalls: ['把 Git 等同 GitHub', '用复制文件夹代替版本历史', '不看差异就提交全部文件'],
    checklist: ['仓库忽略密钥和依赖', '提交前查看 diff', '恢复操作先确认目标范围'],
    related: ['git-workflow', 'commit', 'branch'],
    question: { prompt: 'Git commit 默认保存到哪里？', choices: ['本地仓库历史', '自动上传到 GitHub', '浏览器缓存'], answer: 0, explanation: '提交先进入本地历史，push 才会把提交发送到远程仓库。' }
  }),
  term({
    id: 'commit', title: '提交', english: 'Commit', aliases: ['Git Commit', '版本快照'], category: '工程实践', level: '入门',
    tags: ['Git', '提交', '快照'], excerpt: '把一组相关改动记录为有说明的项目版本。',
    definition: '提交是 Git 历史中的一个不可变记录，包含所选文件变化、作者、时间、说明和父提交关系。',
    why: '聚焦提交让审查者理解意图，也能在问题出现时精确定位和撤销。',
    points: ['先暂存想纳入的变化', '提交信息说明意图', '一个提交保持逻辑完整'],
    example: '“fix: 修复课程目录页内跳转”只包含事件逻辑、样式和对应测试。',
    pitfalls: ['提交信息只写 update', '混入无关格式化', '把未验证代码当恢复点'],
    checklist: ['diff 范围符合任务', '测试已经通过', '没有秘密和临时文件'],
    related: ['git', 'git-workflow', 'pull-request'],
    question: { prompt: '好的提交最重要的特征是什么？', choices: ['表达一个清晰且可验证的意图', '文件数量最多', '信息只写 done'], answer: 0, explanation: '逻辑聚焦且可运行的提交最容易理解、审查和恢复。' }
  }),
  term({
    id: 'branch', title: '分支', english: 'Branch', aliases: ['Git Branch', '代码分支'], category: '工程实践', level: '入门',
    tags: ['Git', '分支', '并行开发'], excerpt: '从某个提交创建独立工作线，安全尝试新变化。',
    definition: '分支是指向某个提交的可移动引用，让不同功能或修复沿各自历史推进。',
    why: '它允许隔离实验和并行协作，但长期不合并的大分支会积累冲突。',
    points: ['从明确基线创建', '名称表达任务目的', '频繁同步主线减少偏离'],
    example: '在 feature/term-atlas 开发词库扩展，验证完成后通过合并请求进入主线。',
    pitfalls: ['一个分支同时处理多个主题', '长期不更新主线', '删除分支前没有确认提交已合并'],
    checklist: ['工作区干净或变化已妥善保存', '分支起点正确', '合并后仍运行完整测试'],
    related: ['git', 'merge', 'pull-request'],
    question: { prompt: '分支的主要用途是什么？', choices: ['隔离一条开发工作线', '替代数据库备份', '加速 CSS'], answer: 0, explanation: '分支让不同变化拥有独立提交历史，再按需要合并。' }
  }),
  term({
    id: 'merge', title: '合并', english: 'Merge', aliases: ['Git Merge', '代码合并'], category: '工程实践', level: '进阶',
    tags: ['Git', '合并', '冲突'], excerpt: '把不同分支的提交历史整合到一起。',
    definition: '合并让 Git 根据共同祖先组合两条分支上的变化，必要时由开发者解决同一区域的冲突。',
    why: '冲突不代表代码一定错误，只说明 Git 无法自动判断应该保留哪种改动。',
    points: ['合并前更新并测试双方代码', '逐段理解冲突意图', '解决后运行受影响测试'],
    example: '详情页样式与目录逻辑修改同一区块时，人工组合两边需要保留的代码。',
    pitfalls: ['看到冲突就全部选择一边', '用删除文件绕过冲突', '合并成功后不运行页面'],
    checklist: ['冲突标记全部清除', '差异中没有重复逻辑', '关键流程重新验证'],
    related: ['branch', 'pull-request', 'testing-strategy'],
    question: { prompt: '解决合并冲突时最重要的动作是？', choices: ['理解双方改动意图后组合并测试', '永远保留较新的文件', '删除冲突文件'], answer: 0, explanation: '时间新旧不能代表业务正确，需要根据意图解决并验证。' }
  }),
  term({
    id: 'pull-request', title: '合并请求', english: 'Pull Request', aliases: ['PR', 'Merge Request', '代码审查'], category: '工程实践', level: '进阶',
    tags: ['Git', '审查', '协作'], excerpt: '在合入主线前展示变化、讨论风险并运行检查。',
    definition: '合并请求是托管平台上的协作流程，集中展示提交、代码差异、测试结果和审查讨论。',
    why: '它不是 Git 本身的命令，而是团队在合并前建立共同理解和质量门槛的工作界面。',
    points: ['标题说明用户可见结果', '描述包含验证证据', '审查意见应具体到风险和行为'],
    example: 'PR 描述列出新增 41 个术语、搜索别名支持以及通过的测试与浏览器截图。',
    pitfalls: ['巨大改动没有说明', '只回复 fixed 不解释如何修复', '测试失败仍直接合并'],
    checklist: ['范围聚焦', '自动检查通过', '审查问题全部解决或记录决策'],
    related: ['commit', 'branch', 'merge'],
    question: { prompt: '合并请求描述最应该包含什么？', choices: ['改了什么、为什么以及如何验证', '只有截图表情', '所有历史聊天'], answer: 0, explanation: '审查者需要范围、动机和证据来判断变化是否安全。' }
  }),
  term({
    id: 'gitignore', title: '忽略文件', english: '.gitignore', aliases: ['Git Ignore', '忽略规则'], category: '工程实践', level: '入门',
    tags: ['Git', '配置', '安全'], excerpt: '声明哪些本地文件和生成物不进入版本控制。',
    definition: '.gitignore 使用路径模式告诉 Git 不跟踪尚未纳入版本历史的文件，例如依赖目录、构建产物和本地密钥文件。',
    why: '它减少仓库噪声并避免误提交秘密，但对已经被 Git 跟踪的文件不会自动取消跟踪。',
    points: ['规则相对仓库目录匹配', '示例配置可提交，真实秘密不可提交', '已跟踪文件需单独移出索引'],
    example: '忽略 node_modules/、dist/ 和 .env，同时提交不含真实值的 .env.example。',
    pitfalls: ['把源代码目录全部忽略', '认为加入规则会删除历史秘密', '忽略锁文件导致安装不一致'],
    checklist: ['git status 不显示生成物', '仓库历史没有密钥', '团队需要的配置示例存在'],
    related: ['git', 'environment-variable', 'deployment'],
    question: { prompt: '.env 已经被提交后，再写进 .gitignore 能从历史删除吗？', choices: ['不能，还需移除跟踪并轮换秘密', '能，历史会自动消失', '只需刷新浏览器'], answer: 0, explanation: '.gitignore 只影响未跟踪文件，已泄露秘密还必须轮换。' }
  }),
  term({
    id: 'build', title: '构建', english: 'Build', aliases: ['打包', 'Compile', 'Bundle'], category: '工程实践', level: '入门',
    tags: ['构建', '打包', '产物'], excerpt: '把源代码转换成可以运行或部署的产物。',
    definition: '构建过程可能编译语法、打包模块、压缩资源、生成静态文件并注入非敏感环境配置。',
    why: '开发环境能运行不代表生产构建一定成功，依赖、路径、大小写和环境配置都可能产生差异。',
    points: ['构建输入来自源代码与依赖', '输出目录通常是生成物', '生产构建应可重复'],
    example: '前端构建把多个模块和样式处理成浏览器可加载的 dist 目录。',
    pitfalls: ['手工修改构建产物', '把服务端密钥打包进客户端', '只测试开发服务器'],
    checklist: ['干净环境可以构建', '产物不包含秘密', '部署前运行生产预览'],
    related: ['deployment', 'performance-budget', 'gitignore'],
    question: { prompt: '为什么不能只验证开发服务器？', choices: ['生产构建的转换和配置可能不同', '开发服务器没有 HTML', '生产不使用浏览器'], answer: 0, explanation: '生产构建会引入压缩、路径和环境差异，必须单独验证。' }
  }),
  term({
    id: 'deployment', title: '部署', english: 'Deployment', aliases: ['Deploy', '发布上线'], category: '工程实践', level: '进阶',
    tags: ['部署', '发布', '生产环境'], excerpt: '把验证过的版本交付到用户可访问的运行环境。',
    definition: '部署是把应用构建产物、服务配置和数据库变化发布到目标环境，并确认系统健康的过程。',
    why: '部署不仅是上传文件，还包括环境变量、迁移、缓存、回滚和上线后监控。',
    points: ['发布内容对应明确版本', '数据库迁移考虑前后兼容', '上线失败有回滚路径'],
    example: '静态学习站发布后检查首页、深层课程地址、移动端布局和缓存更新。',
    pitfalls: ['直接覆盖生产且没有版本记录', '配置缺失仍继续上线', '只看部署成功提示不访问页面'],
    checklist: ['部署前测试通过', '健康检查与关键路径正常', '记录版本和回滚方式'],
    related: ['build', 'environment-variable', 'testing-strategy'],
    question: { prompt: '平台显示部署成功后，下一步应该做什么？', choices: ['访问生产环境验证关键路径', '立即删除旧版本', '关闭所有日志'], answer: 0, explanation: '部署任务完成不代表用户路径正常，还需在真实地址执行验收。' }
  })
];
