export const awakekeeperEnglish = {
  '深夜清醒 · AwakeKeeper': 'AwakeKeeper',
  '为后台任务保持清醒的 macOS 菜单栏工具': 'A macOS menu bar tool that keeps your Mac awake for background tasks',
  'macOS 应用': 'macOS app',
  '本地自用 · 持续迭代': 'Personal local use · In active development',
  '桌面效率与 AI 工作流': 'Desktop productivity and AI workflows',
  '2026.09 — 至今 · v0.3.0': 'Sep 2026 — Present · v0.3.0',
  '后台保活 · 状态反馈 · 自动恢复': 'Keeping tasks running · Status feedback · Automatic recovery',
  '完成真机构建与本地合盖验证，加入中英文切换': 'Built on a physical Mac, verified local lid-closed operation, and added Chinese–English switching',
  '主面板设计预览 · 源自项目仓库的代码布局复刻，非运行截图。': 'Panel design preview · Recreated from the layout in the project code; not a screenshot of the running app.',
  '在 Mac 锁屏或合盖时为后台任务保持运行条件，并通过限时、进程感知与保护机制恢复默认睡眠策略。': 'Keeps a Mac able to run background tasks while locked or with the lid closed, then restores default sleep behavior through time limits, process detection, and protective controls.',
  '运行耗时的 AI 或开发任务时，希望屏幕可以熄灭，也希望离开电脑后任务仍有机会继续。这个工具围绕保活、状态可见和及时停止三个问题展开。': 'Long AI or development tasks should have a chance to continue after the screen turns off or I step away. This tool focuses on keeping the Mac awake, making its state visible, and stopping at the right time.',
  '以菜单栏面板管理两级保活：锁屏级阻止空闲睡眠，屏幕仍可熄灭；合盖级在批准后台帮助程序后启用。支持 macOS 14 及以上的 Apple Silicon Mac，当前按本地自用方式部署。': 'A menu bar panel manages two levels of wake control: lock-screen mode prevents idle sleep while allowing the display to turn off; lid-closed mode requires approval of a background helper. It supports Apple Silicon Macs running macOS 14 or later and is currently deployed for personal local use.',
  '两级保活': 'Two levels of wake control',
  '锁屏与合盖分别控制；合盖模式需要系统批准帮助程序。': 'Lock-screen and lid-closed modes have separate controls; lid-closed mode requires system approval of the helper.',
  '自动规则': 'Automatic rules',
  '按电源或指定进程触发；Claude、Codex、Cursor 等进程全部退出后宽限 60 秒。': 'Trigger by power source or selected processes, with a 60-second grace period after all detected processes such as Claude, Codex, and Cursor exit.',
  '限时与停止': 'Time limits and stopping',
  '设置持续时间、快捷倒计时或停止全部，面板显示当前模式和剩余时间。': 'Set a duration or quick stop timer, or stop everything. The panel shows the active mode and time remaining.',
  '保护与恢复': 'Protection and recovery',
  '低电量停止保活；严重热压力暂停合盖保活；帮助程序用心跳租约处理失联恢复。': 'Low battery stops wake control; serious thermal pressure pauses lid-closed mode. A heartbeat lease lets the helper restore sleep behavior after losing contact with the app.',
  '个人开发项目：围绕自己在 Mac 上运行后台任务的需求，持续推进工具实现、本地使用与界面调整。': 'A personal development project shaped by my own background-task workflow on Mac, with ongoing implementation, local use, and interface refinements.',
  '锁屏与合盖分开：普通保活不需要管理员权限，涉及系统全局睡眠策略的能力单独授权。': 'Separate lock-screen and lid-closed modes: ordinary wake control needs no administrator privileges, while changes to system-wide sleep behavior require separate approval.',
  '自动化保留停止边界：手动停止或到期后暂停自动规则，避免刚停止就被规则重新开启。': 'Make stopping persistent: pause automatic rules after a manual stop or timeout so they cannot immediately turn wake control back on.',
  '只管理自己的状态：检测到外部禁止睡眠设置时提示，不擅自接管或清除其他应用的设置。': 'Manage only its own state: flag sleep prevention set elsewhere without taking over or clearing another app’s settings.',
  '明确保活场景': 'Define when wake control is needed',
  '拆分两级能力': 'Separate the two levels of control',
  '真机构建与联调': 'Build and integrate on a physical Mac',
  '整理使用与恢复边界': 'Document operating and recovery limits',
  '从静态检查走到 Mac 真机，出现了编译兼容与帮助程序连接问题。项目记录显示，后续修复编译错误并调整本地签名校验后，合盖保活取得实测记录；正式分发仍需恢复更严格的签名信任校验。': 'Moving from static checks to a physical Mac exposed compilation compatibility and helper connection issues. Project records document successful local lid-closed operation after compilation fixes and changes to local signature checks. Public distribution still requires restoring stricter signature trust verification.',
  '项目 CHANGELOG 记录：2026.09.13 在 macOS 15 Apple Silicon 上构建无错误、无警告，85 项静态检查通过；本次网站整理未重新运行这些检查。': 'The project CHANGELOG records a build with no errors or warnings on macOS 15 Apple Silicon on September 13, 2026, plus 85 passing static checks. These checks were not rerun for this website update.',
  '0.2.1 更新记录注明：本地 ad-hoc 部署中合盖保活可用，系统睡眠设置生效且帮助程序心跳正常；这不等于所有合盖场景已验收。': 'The 0.2.1 release notes record working lid-closed wake control in a local ad-hoc deployment, with the system sleep setting applied and a healthy helper heartbeat. This does not establish acceptance of every lid-closed scenario.',
  '文档说明因缺少完整 Xcode，XCTest 尚未运行；人工验收清单仍待逐项完成。': 'The documentation states that XCTest has not run because a full Xcode installation was unavailable. The manual acceptance checklist still needs to be completed.',
  '当前版本为 0.3.0，已具备菜单栏操作、自动规则、定时停止及中英文界面。它提供运行条件，不保证任务一定完成：进程存在不等于任务仍在执行，断电或帮助程序被禁用也超出恢复能力。合盖运行需要保持通风，不应把持续运行的设备放入包内。': 'Version 0.3.0 provides menu bar controls, automatic rules, timed stopping, and Chinese and English interfaces. It keeps the Mac able to run tasks but cannot guarantee completion: a running process does not prove a task is still executing, and recovery cannot cover power loss or a disabled helper. Keep the Mac ventilated during lid-closed operation and never place it in a bag while it is running.',
  '这次实践值得保留的一点是：系统工具不只要能开启能力，还要说明当前状态、什么时候停止，以及失败后怎样恢复。编译通过、本地功能走通与适合公开分发，是不同的阶段。': 'One lesson from this project: a system utility must explain its current state, when it will stop, and how it recovers from failure, as well as enable a capability. A successful build, working local functionality, and readiness for public distribution are separate milestones.',
  '补齐完整 Xcode 下的单元测试和 Mac 人工验收。': 'Run the unit tests with a full Xcode installation and complete manual acceptance testing on Mac.',
  '继续验证低电、热压力、应用退出与帮助程序异常时的恢复路径。': 'Continue verifying recovery paths for low battery, thermal pressure, app exit, and helper failures.',
  '公开分发前完成 Developer ID 签名、严格对端校验与分发验收。': 'Complete Developer ID signing, strict peer verification, and distribution acceptance checks before public distribution.',
  'Core、Platform、App、Helper 与 Shared 分层': 'Layered Core, Platform, App, Helper, and Shared modules',
  '功能迭代': 'Feature iteration',
  '让菜单栏、设置与关于窗口支持双语': 'Bring two languages to the menu bar, settings, and About window',
  '0.3.0 加入中英文即时切换，并在本地记住选择。': 'Version 0.3.0 adds instant Chinese–English switching and remembers the choice locally.',
  '让工具的状态、设置和使用说明在两种语言下保持一致。': 'Keep status messages, settings, and usage guidance consistent in both languages.',
  '新增统一语言管理和文案表，接入主面板、设置与关于窗口。': 'Add shared language management and a text catalog, then connect the main panel, settings, and About window.',
  '依据 CHANGELOG 0.3.0 与 Language.swift 整理，版本号为 0.3.0（4）。': 'Based on CHANGELOG 0.3.0 and Language.swift; the version is 0.3.0 (4).',
  '语言切换覆盖状态反馈和说明文字，后续还需要持续检查长文案与窗口布局。': 'Language switching covers status feedback and explanatory text. Longer copy and window layouts still need ongoing checks.',
  '验证记录': 'Verification record',
  '从静态检查走到 Mac 真机联调': 'Move from static checks to integration on a physical Mac',
  '修复首次编译问题，并取得本地合盖保活的验证记录。': 'Fix the first compilation issues and record verification of local lid-closed wake control.',
  '确认原生代码可以在目标 Mac 上构建，并连接合盖帮助程序。': 'Confirm that the native code builds on the target Mac and connects to the lid-closed helper.',
  '修复编译兼容问题，调整本地 ad-hoc 部署的 XPC 对端要求。': 'Fix compilation compatibility issues and adjust XPC peer requirements for local ad-hoc deployment.',
  '依据 CHANGELOG 0.2.0 和 0.2.1：构建与静态检查通过，合盖设置生效、心跳正常；本次未重跑。': 'According to CHANGELOG 0.2.0 and 0.2.1, the build and static checks passed, the lid-closed setting took effect, and the heartbeat was healthy. These checks were not rerun here.',
  '当前只校验对端 bundle 标识，不能等同正式签名分发；完整测试与异常场景验收仍需补齐。': 'Current verification checks only the peer’s bundle identifier, which is not equivalent to formally signed distribution. Full tests and acceptance checks for failure scenarios remain outstanding.',
};
