import { esc } from '../../shared/components/content-detail.js';
import { isPublished, safeHref } from '../../shared/content/validation.js';
import { icon } from '../learning/home-sections.js';
import { sectionHead, contentCard, linkTo, endcap, searchPanel, searchResults } from './explore.js';
import { thinkingArticles } from './thinking-details.js';
import { projectCover } from '../work/presentation.js';

export function thinkingCatalog(notes=[]){return [...notes.filter(isPublished).map(n=>({id:n.id,title:n.title,summary:n.oneLiner||n.myTake,category:n.kind==='LOG'?'复盘':'笔记',tags:[n.category],href:'#/notes/'+n.id,status:'已发布',icon:'book'})),...thinkingArticles.map(n=>({...n,href:'#/notes/'+n.id,status:'内容草稿',tags:['文章'],icon:n.layout?'cube':'bulb'}))];}
export function thinkingDepth(notes=[]){const published=notes.filter(isPublished);const groups=[['产品与内容的取舍','从一个界面或一种内容结构出发，记录分析的角度与选择。',['website-comparison','homepage-actions']],['方法与复盘','把做事的过程留下来，也为下一次判断留下依据。',['project-retro','content-boundaries']]];return `${published.length?`<section class="ex-section">${sectionHead('NOTES / 真实记录','先留下正在形成的理解','这些已经发布的记录，来自网站搭建和内容整理的过程。')}<div class="ex-journal">${published.map((n,i)=>`<article><small>${esc(n.date||'')} · ${esc(n.category||'笔记')}</small><div><h3>${linkTo('#/notes/'+n.id,n.title)}</h3><p>${esc(n.question||n.oneLiner)}</p><blockquote>${esc(n.myTake||n.myUnderstanding)}</blockquote></div><span class="ex-journal-number" aria-hidden="true">0${i+1}</span></article>`).join('')}</div></section>`:''}<section class="ex-section">${sectionHead('IN PROGRESS / 正在整理','沿着不同的主题，继续思考','以下为内容草稿，保留当前观点与写作方向。')}${groups.map(([title,description,ids])=>`<div class="ex-topic-block"><div class="ex-topic-intro">${icon('bulb','green')}<h3>${title}</h3><p>${description}</p></div><div class="ex-grid">${thinkingCatalog().filter(n=>ids.includes(n.id)).map(contentCard).join('')}</div></div>`).join('')}</section>${endcap('记录、实践，再回过头想一想。','从学习记录继续阅读，也可以回到项目中了解这些想法的背景。','#/learning','查看学习记录')}`;}
export function projectDepth(projects){return `<section class="ex-section" id="project-stories">${sectionHead('PROJECT STORIES / 逐个了解','每个想法，都有一段实践过程','从具体问题出发，看方案如何形成，以及接下来要验证什么。')}${projects.map((p,i)=>`<article class="ex-project-story" id="story-${esc(p.id)}"><header><small>PROJECT ${String(i+1).padStart(2,'0')}</small><span class="cl-tag">${esc(p.statusLabel||'持续完善')}</span></header><div class="ex-project-body"><div><h2>${esc(p.displayTitle||p.title)}</h2><p class="ex-project-subtitle">${esc(p.subtitle||'')}</p><h3>从什么问题开始</h3><p>${esc(p.problem||p.summary)}</p><h3>目前的方案</h3><p>${esc(p.solution||p.summary)}</p>${linkTo('#/projects/'+p.id,'阅读完整项目过程')}</div><div class="ex-project-visual">${projectCover(p)}</div></div>${p.modules?.length?`<div class="ex-project-modules">${p.modules.slice(0,4).map(([t,d],i)=>`<div>${icon(['cube','layers','file','refresh'][i],i%2?'blue':'green')}<h3>${esc(t)}</h3><p>${esc(d)}</p></div>`).join('')}</div>`:''}${p.nextSteps?.length?`<div class="ex-next"><strong>下一步</strong><p>${p.nextSteps.map(esc).join(' · ')}</p></div>`:''}</article>`).join('')}</section>${endcap('实践中的问题，会成为下一次学习的起点。','继续查看与产品、开发和 AI 协作有关的知识。','#/learning?kind=CONCEPT','进入知识')}`;}
export function resourceCatalog(tools=[],library=[]){return [...tools.filter(isPublished).map(t=>({id:t.id,title:t.title,summary:t.problemSolved||t.subtitle,category:t.type==='CHECKLIST'?'清单':t.type==='PROMPT'?'Prompt':'工具',tags:[t.category,t.typeLabel],href:'#/toolbox/'+t.id,icon:t.type==='CHECKLIST'?'file':'code'})),...library.filter(isPublished).filter(x=>safeHref(x.url)).map(x=>({id:x.id,title:x.id==='lib-vibe-hub'?'MDN Web Docs':x.title,summary:x.id==='lib-vibe-hub'?'查阅 Web 标准、开发文档和学习路径。':`${x.author||'外部来源'} · ${(x.tags||[]).join(' / ')}`,category:x.type==='GITHUB'?'开源':'网站',tags:x.tags||[],href:x.url,external:true,icon:'link'}))];}
function resourceFeature(item, tools){const tool=tools.find(t=>t.id===item.id);if(!tool)return contentCard(item);return `<article class="cl-card ex-resource-feature"><div>${icon(item.icon,'green')}<small>${esc(item.category)}</small><h3>${esc(item.title)}</h3><p>${esc(item.summary)}</p>${linkTo(item.href,'查看使用说明')}</div><div><h3>${tool.checklist?.length?'发布前，逐项确认':'使用路径'}</h3><ol>${(tool.checklist||tool.steps||[]).map(x=>`<li>${typeof x==='string'?esc(x):`<strong>${esc(x.title)}</strong><p>${esc(x.detail)}</p>`}</li>`).join('')}</ol></div></article>`;}
export function renderResourcesColumn(tools=[],library=[]){const all=resourceCatalog(tools,library);const groups=[['开发与协作','减少环境配置与重复操作，把时间留给真正的问题。',all.filter(x=>x.category==='工具')],['内容整理与发布','写完之后再检查一遍，让内容表达清楚、来源可查。',all.filter(x=>x.category==='清单'||x.category==='Prompt')],['学习与理解 AI','从已有资料架中继续查阅教程、协议与开源项目。',all.filter(x=>x.external)]];return `<section class="cl-page ex-page site-container"><div class="cl-hero"><header class="cl-heading"><p class="hp-label">资源 / Resources</p><h1>把值得反复使用的东西，<br>整理成自己的资源库。</h1><p>工具、清单和参考资料，围绕具体场景整理。<br>找到现在能用上的，也为下次查找留一个入口。</p></header>${searchPanel('搜索工具、清单、Prompt、MCP …',['工具','清单','网站','开源'])}</div>${searchResults}<div data-ex-default><div class="ex-resource-intro cl-card"><div>${icon('layers','green')}<h2>从手头的任务开始</h2><p>查看用途，再决定是否适合自己的工作方式。</p></div><div class="ex-resource-count"><strong>${all.length}</strong><span>条已有资源</span><small>工具与资料架统一浏览</small></div></div>${groups.map(([title,description,items],i)=>items.length?`<section class="ex-section">${sectionHead('0'+(i+1)+' / 使用场景',title,description)}<div class="ex-grid ${i===2?'ex-grid-three':''}">${items.length===1&&!items[0].external?resourceFeature(items[0],tools):items.map(contentCard).join('')}</div></section>`:'').join('')}<section class="ex-section cl-card ex-resource-guide">${sectionHead('REUSE / 如何使用','找到之后，让它真正帮上忙','根据资源类型选择下一步。')}<div class="ex-grid-three">${[['code','工具与脚本','进入使用说明，了解用途、环境与操作步骤。'],['file','清单与模板','在具体任务中检查和复用，按自己的需要调整。'],['link','外部资料','带着问题访问原始来源，结合实践形成自己的理解。']].map(([i,t,d])=>`<div>${icon(i)}<h3>${t}</h3><p>${d}</p></div>`).join('')}</div></section>${endcap('需要专门查找外部资料？','资料架保留网站、文章与开源仓库的集中入口。','#/library','打开资料架')}</div></section>`;}
export function aboutDepth(){return `<section class="ex-section">${sectionHead('WHY / 从学习开始','让过程有迹可循，让理解慢慢生长','这个网站随着学习、尝试和整理一起变化。')}<div class="ex-about-story"><div class="cl-card"><h3>先把一个问题理解清楚</h3><p>遇到不熟悉的概念时，先写下它是什么、为什么需要它，再用例子确认自己的理解。</p>${linkTo('#/learning?kind=CONCEPT','看看我的知识记录')}</div><div class="cl-card"><h3>再把理解放进真实的实践</h3><p>从这个网站和正在设计开发的小产品开始，把选择、困难和下一步都留下来。</p>${linkTo('#/projects','了解正在做的项目')}</div><div class="cl-card"><h3>最后留下一点可复用的方法</h3><p>将实践中的经验整理成笔记、清单和工具，方便自己回看，也让他人找到可参考的内容。</p>${linkTo('#/about/me','阅读完整的建站故事')}</div></div></section><section class="ex-section cl-card ex-bridge">${sectionHead('NOW / 持续推进','现在的方向，也会继续更新','继续完善网站内容结构，推进滑一叠的设计开发，整理产品开发的方法。')}<div class="ex-grid">${contentCard({title:'当前正在做的事',category:'关于 / Now',summary:'查看正在推进的方向，以及这个网站适合怎样阅读。',href:'#/about/now',icon:'refresh'})}${contentCard({title:'从记录开始认识这里',category:'思考 / Notes',summary:'了解网站为什么以学习、实践和整理作为内容主线。',href:'#/notes/why-record-learning',icon:'book'})}</div></section>`;}
