import {bilingualText} from '../../app/language.js';
import { terminologyCategories, terminologyGroups } from '../topics/glossary.js';
import { esc } from '../../shared/components/content-detail.js';
import { isPublished, safeHref } from '../../shared/content/validation.js';
import { icon } from '../learning/home-sections.js';
import { seriesDefinitions, knowledgeTitle, categoryFor } from './knowledge-data.js';

export const sectionHead=(eyebrow,title,description,link='')=>`<header class="ex-section-head"><div><small>${esc(eyebrow)}</small><h2>${esc(title)}</h2><p>${esc(description)}</p></div>${link}</header>`;
export const linkTo=(href,title)=>`<a class="ex-link" href="${esc(href)}">${esc(title)} <span aria-hidden="true">→</span></a>`;
export function contentCard(x){return `<a class="cl-card ex-content-card" href="${esc(safeHref(x.href))}" ${x.external?'target="_blank" rel="noopener noreferrer"':''}>${icon(x.icon||'file',x.tone||'blue')}<div><small>${esc(x.category||'')} ${x.status?'· '+esc(x.status):''}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary||'')}</p></div><span class="cl-arrow" aria-hidden="true">${x.external?'↗':'→'}</span></a>`;}
export const topicCategory=categoryFor;
export function knowledgeCatalog(topics){return [...topics.filter(isPublished).map(t=>({id:t.id,title:knowledgeTitle(t),category:topicCategory(t),tags:[t.category,t.subcategory,t.english,...(t.aliases||[]),...(t.tags||[])],subcategory:t.subcategory,summary:t.excerpt||t.definition||'',href:`#/topics/${encodeURIComponent(t.id)}`,icon:topicCategory(t)==='产品'?'cube':'file'})),...seriesDefinitions.map(s=>({ ...s,category:'系列',tags:[s.category],href:`#/topics/${s.id}`,icon:'layers',status:'持续整理'}))];}
export function searchPanel(placeholder,categories){return `<div class="ex-search"><label class="hp-search">${icon('search')}<input type="search" data-ex-query aria-label="搜索栏目全部内容" placeholder="${esc(placeholder)}"></label><div class="hp-filters">${['全部',...categories].map((s,i)=>`<button type="button" data-ex-filter="${i?esc(s):''}" aria-pressed="${!i}">${esc(s)}</button>`).join('')}</div><small>搜索本栏目全部内容</small></div>`;}
export const searchResults='<section class="ex-results" data-ex-results hidden aria-label="搜索结果"><header class="ex-section-head"><h2 tabindex="-1">搜索结果</h2><button type="button" data-ex-reset>清除筛选</button></header><p data-ex-count role="status" aria-live="polite"></p><div class="ex-grid" data-ex-cards></div><p data-ex-empty hidden>没有找到匹配内容，试试其他关键词或清除筛选。</p></section>';
export function filterCatalog(items,query='',category=''){const words=query.trim().toLowerCase().split(/\s+/).filter(Boolean);return items.filter(x=>(!category||x.category===category||(x.tags||[]).includes(category))&&words.every(w=>bilingualText([x.title,x.summary,x.category,...(x.tags||[])]).toLowerCase().includes(w)));}
export function mountExplore(root,items,params=new URLSearchParams()){
 const input=root.querySelector('[data-ex-query]');if(!input)return;
 const buttons=[...root.querySelectorAll('[data-ex-filter]')];let category=params.get('category')||'';
 if(!buttons.some(b=>b.dataset.exFilter===category))category='';input.value=params.get('q')||'';
 const update=()=>{const active=!!(input.value.trim()||category);root.querySelector('[data-ex-results]').hidden=!active;root.querySelectorAll('[data-ex-default]').forEach(x=>x.hidden=active);buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.exFilter===category)));const found=filterCatalog(items,input.value,category);root.querySelector('[data-ex-count]').textContent=`找到 ${found.length} 条内容`;root.querySelector('[data-ex-cards]').innerHTML=active?found.map(contentCard).join(''):'';root.querySelector('[data-ex-empty]').hidden=found.length>0;const [path,query='']=location.hash.split('?');const next=new URLSearchParams(query);for(const [k,v] of [['q',input.value.trim()],['category',category]]){if(v)next.set(k,v);else next.delete(k);}history.replaceState(null,'',path+(next.size?'?'+next:''));};
 input.addEventListener('input',update);buttons.forEach(b=>b.addEventListener('click',()=>{category=b.dataset.exFilter;update();}));root.querySelector('[data-ex-reset]').addEventListener('click',()=>{category='';input.value='';update();input.focus();});update();
}
export function knowledgeDepth(topics){const catalog=knowledgeCatalog(topics);const featured=new Set(['rag','mvp','user-flow']);const groups=terminologyCategories.map(c=>[c,c+'知识',terminologyGroups[c].join(' · ')] );return `<section class="ex-section" id="knowledge-themes">${sectionHead('EXPLORE / 按主题深入','从一个问题，继续读下去','选择正在关心的方向，找到下一条值得理解的知识。')}${groups.map(([c,t,d])=>{const all=catalog.filter(x=>x.category===c&&!featured.has(x.id)&&!x.id.startsWith('ai-product-')&&!x.id.startsWith('website-lab-')&&!x.id.startsWith('git-lab-'));return all.length?`<div class="ex-topic-block"><div class="ex-topic-intro">${icon(c==='产品'?'cube':c==='开发'?'code':'layers',c==='AI'?'green':'blue')}<h3>${t}</h3><p>${d}</p><div class="ex-subcategory-links">${terminologyGroups[c].map(g=>linkTo('#/topics?category='+encodeURIComponent(c)+'&subcategory='+encodeURIComponent(g),g)).join('')}</div>${linkTo('#/topics?category='+encodeURIComponent(c),'浏览这一主题')}</div><div class="ex-grid">${all.slice(0,4).map(contentCard).join('')}</div></div>`:'';}).join('')}</section><section class="ex-section">${sectionHead('LEARNING PATH / 系列学习','把零散知识，串成一条路径','按自己的问题选择章节，或沿着系列逐步深入。')}<div class="ex-series-grid">${seriesDefinitions.map(s=>{const available=s.chapters.filter(([, ,id])=>topics.some(t=>t.id===id&&isPublished(t)));return `<article class="cl-card ex-series"><div>${icon('book','green')}<small>${available.length} 个已有章节 · 持续整理</small></div><h3>${s.title}</h3><p>${s.summary}</p><ol>${s.chapters.slice(0,5).map(([title,description,id])=>`<li>${topics.some(t=>t.id===id&&isPublished(t))?linkTo('#/topics/'+id,title):`<span>${title}<small>整理中</small></span>`}<p>${description}</p></li>`).join('')}</ol>${linkTo('#/topics/'+s.id,'查看完整系列')}</article>`;}).join('')}</div></section><section class="ex-section ex-bridge cl-card">${sectionHead('KNOWLEDGE → PRACTICE','让知识有实际的落点','从概念出发，再去看看它连接的项目与整理方法。')}<div class="ex-grid">${[{title:'AI Learning OS',summary:'把内容结构和界面状态用在这个学习网站中。',category:'项目实践',href:'#/projects/learning-site',icon:'cube'},{title:'一条学习记录的发布检查',summary:'写完之后，用一份清单检查表达、来源和阅读体验。',category:'可复用资源',href:'#/toolbox/content-publish-checklist',icon:'file'}].map(contentCard).join('')}</div></section>${endcap('带着问题来，也可以随意翻一翻。','全部知识支持检索与分类，方便下一次回来查阅。','#/topics','浏览全部知识')}`;}
export const endcap=(title,description,href,label)=>`<section class="ex-endcap"><div><h2>${esc(title)}</h2><p>${esc(description)}</p></div>${linkTo(href,label)}</section>`;
