import { terminologyCategories } from '../topics/glossary.js';
import { seriesDefinitions } from './knowledge-data.js';
import { knowledgeDepth, searchPanel, searchResults } from './explore.js';
import { thinkingDepth, aboutDepth } from './depth.js';
import { esc } from '../../shared/components/content-detail.js';
import { isPublished } from '../../shared/content/validation.js';
import { icon, attrs, chips, peek, empty } from '../learning/home-sections.js';
import { knowledgeSelection, seriesSelection, thinkingSelection } from '../learning/home-curation.js';
export const columnTail = '<footer class="cl-tail"><span>THINK · BUILD · SHARE · GROW</span><span>—— 想与做，和更好的可能性在一起。</span></footer>';
const dialog = '<dialog class="hp-preview-dialog"><button type="button" data-hp-close aria-label="关闭预览">×</button><p class="hp-dialog-status"></p><h2></h2><p class="hp-dialog-body"></p><a href="#/learning">浏览已有学习记录 →</a></dialog>';
const heading=(label,title,body)=>`<header class="cl-heading"><p class="hp-label">${label}</p><h1>${title}</h1><p>${body}</p></header>`;
const search=(placeholder,categories)=>`<div class="cl-search-area"><label class="hp-search">${icon('search')}<input type="search" data-hp-search aria-label="搜索栏目内容" placeholder="${placeholder}"></label>${chips(categories)}<div class="cl-pinned" aria-hidden="true">Better<br>Ideas<br>Together :)</div></div>`;
const sectionTitle=(title,link='')=>`<div class="cl-section-title"><h2>${title}</h2>${link}</div>`;
export function windowSketch(){return '<div class="cl-window-art" aria-hidden="true"><img src="./assets/columns/projects-reference.png" alt=""></div>';}
function knowledgeCard(x,topics){const found=topics.find(t=>t.id===x.id&&isPublished(t));const tag=found?'a':'button';return `<${tag} class="cl-card cl-knowledge-card" ${found?`href="#/topics/${encodeURIComponent(x.id)}"`:peek(x)} ${attrs(x)}>${icon(x.icon,x.tone)}<div><h3>${esc(x.title)}</h3><small>${esc(x.meta)}</small><p>${esc(x.summary)}</p></div><span class="cl-arrow">→</span></${tag}>`;}
export function renderKnowledgeColumn(topics=[]){
 const items=[...knowledgeSelection,{id:'mcp',title:'MCP 是什么？',category:'AI',meta:'AI · 知识',summary:'模型、工具和上下文如何协同？',icon:'layers'}, {id:'prompt-workflow',title:'Prompt 与 Workflow 的区别',category:'Agent',meta:'Agent · 知识',summary:'为什么重复工作需要结构化流程？',icon:'tree',tone:'purple'}];
 return `<section class="cl-page site-container" ><div class="cl-hero">${heading('知识 / Knowledge','把没弄懂的问题，<br>整理成可反复查阅的知识。','这里整理我在学习的 AI、产品、开发与工作流知识，<br>也会把一些连续主题做成系列，方便回看和继续深化。')}${searchPanel('搜索：RAG / MVP / Agent / PRD …',[...terminologyCategories,'系列'])}</div>${searchResults}<div data-ex-default><div class="cl-knowledge-layout"><div>${sectionTitle('最近知识','<a href="#/topics">全部知识 →</a>')}<div class="cl-knowledge-grid">${items.slice(0,3).map(x=>knowledgeCard(x,topics)).join('')}</div>${empty}${sectionTitle('知识系列')}<div class="cl-series-grid">${seriesDefinitions.map((x,i)=>`<a class="cl-card cl-series-card" href="#/topics/${x.id}">${icon(x.icon||'book')}<div><h3>${x.title}</h3><small>${x.chapters.length} 章 · ${x.category}</small><p>${x.summary}</p></div><span class="cl-series-state">可阅读</span><span class="cl-arrow">→</span></a>`).join('')}</div></div><aside class="cl-knowledge-aside"><h2>在这里你会看到</h2>${[['file','知识点','关键概念、原理与实践方法','green'],['layers','系列内容','系统化的主题学习路径','blue'],['link','相关项目链接','与实际项目和案例建立连接','purple']].map(([i,t,p,c])=>`<div>${icon(i,c)}<div><h3>${t}</h3><p>${p}</p></div></div>`).join('')}<p class="cl-aside-quote">知识不是堆积，而是为了下一次更快理解。</p></aside></div>${knowledgeDepth(topics)}</div>${columnTail}${dialog}</section>`;
}
export function renderThinkingColumn(notes=[]){const [featured,...rest]=thinkingSelection;const items=[...rest,{title:'我现在怎么区分知识、思考和资源？',category:'笔记',meta:'网站规划',summary:'随着内容越来越多，重新梳理这三个栏目的边界和关系，让它们在知识体系中各自更清晰。',icon:'layers'}].map((x,i)=>({...x,category:['产品拆解','文章','文章','复盘','笔记'][i]}));return `<section class="cl-page cl-thinking site-container" ><div class="cl-hero">${heading('思考 / Thinking','把理解、判断和复盘，<br>写成自己的思考。','这里记录自己的笔记、文章、产品拆解、竞品分析和不断演化的观点，<br>让学习不只是停留在信息层面，而是逐渐变成自己的判断。')}${searchPanel('搜索文章、笔记、拆解、复盘 …',['笔记','方法','产品拆解','竞品分析','复盘'])}</div>${searchResults}<div data-ex-default><div class="cl-thinking-feature"><div>${sectionTitle('本周思考')}<a class="cl-card cl-feature" href="#/notes/ai-collaboration"><div class="cl-paper-art" aria-hidden="true"><img src="./assets/columns/thinking-reference.png" alt=""></div><div><span class="cl-feature-label">✦ 精选文章 · 整理中</span><h2>${featured.title}</h2><div class="cl-tags"><span>方法</span><span>AI Product</span></div><p>${featured.summary}</p><small>选题已确定 · 正文整理中</small></div><span class="cl-arrow">→</span></a></div><aside><div class="cl-card cl-explainer"><h2>${icon('grid')}这个栏目里会有什么</h2>${[['book','笔记','记录日常的学习笔记与灵感想法'],['cube','拆解','产品拆解，关注设计、逻辑与细节'],['tree','分析','对行业、产品和趋势的观察与分析'],['refresh','复盘','记录项目与决策的过程，提炼经验']].map(([i,t,d])=>`<div>${icon(i)}<strong>${t}</strong><p>${d}</p></div>`).join('')}</div><blockquote class="cl-card cl-small-quote">思考不是总结结束，而是为了下一次做得更清楚。<cite>—— 想与做</cite></blockquote></aside></div>${sectionTitle('选题速览','<a href="#/notes/website-comparison">竞品分析 →</a>')}<div class="cl-thinking-grid">${items.slice(0,2).map((x,i)=>`<a class="cl-card cl-thinking-card" href="#/notes/${['vibehub-structure','prompt-to-workflow','homepage-actions','project-retro','content-boundaries'][i]}" ${attrs(x)}><header>${icon(x.icon,x.tone)}<h3>${esc(x.title)}</h3><span class="cl-arrow">→</span></header><span class="cl-tag">${esc(x.meta)}</span><p>${esc(x.summary)}</p><small>内容草稿</small></a>`).join('')}</div>${empty}${thinkingDepth(notes)}</div>${columnTail}${dialog}</section>`;}
export function renderAboutColumn(){return `<section class="cl-page cl-about site-container"><div class="cl-about-hero"><div>${heading('关于 / About','我在学习 AI，<br>也在把它做成真实的东西。','这是我用来记录 AI 学习、产品实践和个人思考的网站。<br>我希望把知识、项目和可复用的方法连接起来，<br>慢慢构建一个不断成长的个人系统。')}<div class="cl-tags cl-about-tags"><span>AI Product</span><span>Agent</span><span>Building</span></div><a class="zh-button zh-button--primary" href="#/projects">查看我做的项目 →</a></div><div class="cl-card cl-focus"><div class="cl-focus-top"><div class="cl-avatar"><img src="./assets/hero/person-hero.png" alt="想与做的人物插画"></div><div><h2><a href="#/about/now">现在我在做什么 →</a></h2><ul><li>持续整理 AI Learning OS</li><li>设计与开发滑一叠的小程序体验</li><li>把方法沉淀成知识与资源</li></ul></div></div><div class="cl-focus-bottom"><small>Current Focus · 2026</small>${windowSketch()}</div></div></div><div class="cl-about-grid"><article class="cl-card"><header>${icon('cube','green')}<div><h2>我在关注什么</h2><p>这些是我持续探索的方向。</p></div></header><div class="cl-tags"><span>AI Product</span><span>Agent</span><span>产品实践</span><span>知识系统</span></div></article><article class="cl-card"><header>${icon('grid')}<div><h2>我怎么做事</h2><p>从问题到实践，再到沉淀。</p></div></header><div class="cl-method">${[['bulb','理解问题'],['code','动手实践'],['tree','验证结果'],['file','复盘沉淀']].map(([i,t])=>`<div>${icon(i)}<span>${t}</span></div>`).join('')}</div></article><article class="cl-card"><header>${icon('book','green')}<div><h2><a href="#/about/me">为什么做这个网站 →</a></h2><p>把零散学习和项目经验，<br>慢慢变成能复用的个人系统。</p></div></header><p class="cl-handwritten">Better Thinking.<br>A Better Me.</p></article></div>${aboutDepth()}<div class="cl-card cl-contact"><div>${icon('link')}<div><h3>联系我</h3><p>欢迎交流 AI、产品或任何有趣的想法。</p></div></div><a href="https://github.com/Yiyang0659" target="_blank" rel="noopener noreferrer"><strong>GitHub ↗</strong><span>github.com/Yiyang0659</span></a><a href="#/learning?kind=CONCEPT"><strong>我的知识库 →</strong><span>学习与实践的记录</span></a><p>让 AI 更好地服务真实的生活。<br>—— 想与做</p></div>${columnTail}</section>`;}
