import { esc, safeText } from './support.js';
import { icon } from '../learning/home-sections.js';
import { columnTail } from './pages.js';
export const thinkingArticles=[
 {id:'ai-collaboration',title:'为什么我不再把开发全部交给 AI',category:'方法',summary:'AI 提升了开发效率，但清晰的问题、边界与判断仍然需要自己负责。这是一份根据页面设计整理的文章草稿。',sections:[['先说结论','把 AI 当作行动助手，自己负责方向、边界、取舍和验证。'],['我以前是怎么做的','从自然语言描述开始，让 AI 生成代码、调整样式、修复问题。这样的方式启动很快，但项目复杂之后，需要更多结构化的约束。'],['问题出在哪里',['缺少方法：需求临时描述，容易反复修改。','范围不清：没有明确目标和边界，容易偏离预期。','难以复现：缺少过程记录，后续难以继续迭代。']],['我现在的做法','先写 Brief、梳理结构、设定优先级，再分步骤执行和验证。'],['一个具体例子','在这个个人网站的设计过程中，先确定首页前两屏，再整理统一的边距、字体和页面规范，最后逐步扩展栏目与详情页。'],['My Take','AI 能帮助更快地把想法变成现实。明确的目标、自己的判断与持续验证，决定最终结果是否有用。'],['接下来怎么做',['开发前先写清楚目标与非目标。','保留可复用的页面规范与工作流程。','持续复盘，让下一次协作更清晰。']]]},
 {id:'vibehub-structure',title:'VibeHub 的知识结构，有哪些值得借鉴？',category:'产品拆解',summary:'根据提供的设计方案，梳理知识网站在内容组织、导航和学习路径上的可借鉴之处。以下为拆解草稿，具体产品观察仍待补充验证。',layout:'teardown'},
 {id:'website-comparison',title:'知识型个人网站，内容结构应该怎么取舍？',category:'竞品分析',summary:'从内容密度、导航结构、个人表达、可扩展性和作品展示能力几个维度，比较不同网站方向。以下为设计方案中的定性分析。',layout:'comparison'},
 {id:'prompt-to-workflow',title:'从 Prompt 到 Workflow，我的理解发生了什么变化？',category:'方法',summary:'把单次提问整理成可重复的步骤，让输入、输出和验证方式逐渐清晰。',sections:[['从单次问题开始','Prompt 帮助表达目标，但重复工作还需要固定的输入和输出。'],['把流程写下来','将复杂任务拆成明确步骤，标记需要人工确认的地方。'],['让结果可以验证','用样例检查每一步输出，并记录下一次要改进的地方。']]},
 {id:'homepage-actions',title:'一个首页为什么不能有太多按钮？',category:'产品思考',summary:'结合首页的几轮调整，整理主要行动与辅助入口之间的层级。',sections:[['先明确主要行动','首屏用一个核心表达、一个当前项目和一个主要行动组织阅读。'],['把信息和操作分开','项目状态和内容数量是说明信息，不一定都需要变成按钮。'],['为下一步留出方向','次级入口应当可识别，但不与主要行动争夺注意力。']]},
 {id:'project-retro',title:'做项目时，我越来越重视复盘这一步',category:'复盘',summary:'把问题、选择和观察结果留下来，让下一次判断有迹可循。',sections:[['记录发生了什么','保留原目标与实际结果之间的差异。'],['理解为什么这样做','写下关键选择、约束和未验证的判断。'],['确定下一次行动','明确需要保留、改变和继续验证的内容。']]},
 {id:'content-boundaries',title:'我现在怎么区分知识、思考和资源？',category:'网站规划',summary:'知识解释概念，思考留下判断，资源保存可复用的方法与工具。',sections:[['知识','围绕具体概念、原理和实践方法组织内容。'],['思考','记录分析、取舍和阶段性的判断。'],['资源','整理可直接复用的提示词、清单和流程。']]}
];
const articleLinks=()=>thinkingArticles.slice(0,3).map(x=>`<a class="ds-related-link" href="#/notes/${x.id}"><strong>${x.title}</strong><span>→</span></a>`).join('');
const heading=x=>`<header class="cl-heading"><p class="hp-label">思考 / ${x.category}</p><h1>${x.title}</h1><small>${x.category} · 内容草稿</small><p>${x.summary}</p></header>`;
const cards=items=>`<div class="ds-analysis-cards">${items.map(([i,t,d])=>`<article class="cl-card">${icon(i)}<div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div>`;
export function renderThinkingDetail(id){const x=thinkingArticles.find(x=>x.id===id);if(!x)return '';if(x.layout==='teardown')return teardown(x);if(x.layout==='comparison')return comparison(x);return `<article class="cl-page ds-reading site-container"><p class="hp-label">思考 / Thinking</p><div class="ds-reading-layout"><aside class="cl-card ds-left"><nav>${['全部','方法','产品思考','复盘','网站规划'].map((t,i)=>`<a href="#/learning?kind=NOTE">${icon(['grid','bulb','cube','file','layers'][i])}${t}</a>`).join('')}</nav><h3>相关主题</h3><a class="ds-related-link" href="#/topics/series-product">产品实践 →</a><a class="ds-related-link" href="#/topics/mvp">MVP →</a><a class="ds-related-link" href="#/topics/series-agent">Workflow →</a></aside><div class="cl-card ds-article ds-editorial"><header><small><a href="#/learning?kind=NOTE">思考</a> / ${x.category} · 内容草稿</small><h1>${x.title}</h1><p>${x.summary}</p></header>${x.sections.map(([title,body],i)=>`<section id="thought-${i}" class="${title==='My Take'?'ds-take':''}"><h2><b>${i+1}</b>${title}</h2>${safeText(body)}${title==='我现在的做法'?cards([['file','1. 写 Brief','明确目标、用户和问题'],['layers','2. 梳理结构','拆解功能与信息'],['grid','3. 设定优先级','确定最小范围'],['code','4. AI 执行','生成、检查、迭代']]):''}</section>`).join('')}<div class="ds-bottom-links"><a href="#/learning?kind=NOTE">← 返回思考</a><a href="#/notes/website-comparison">继续阅读 →</a></div></div><aside class="ds-right"><div class="cl-card"><h2>${icon('file','green')}本页提要</h2><nav class="ds-toc">${x.sections.map(([t],i)=>`<a href="#/notes/${x.id}" data-ds-scroll="thought-${i}">${t}</a>`).join('')}</nav></div><div class="cl-card"><h2>${icon('book')}继续阅读</h2>${articleLinks()}</div></aside></div>${columnTail}</article>`;}
function teardown(x){return `<article class="cl-page ds-analysis site-container"><div class="ds-analysis-layout"><div><div class="ds-teardown-hero">${heading(x)}<div class="cl-card ds-mini-sites" aria-label="内容结构对比示意">${['VibeHub','想与做'].map((t,i)=>`<div><strong>${t}</strong><div class="ds-mini-search">搜索学习内容 …</div><div class="ds-mini-body"><aside>首页<br>知识<br>项目<br>思考</aside><section><h3>${i?'把想法变成<br>可实践的作品':'从问题出发，<br>系统地学习'}</h3><i></i><i></i><i></i><b></b></section></div><p>${i?'更轻量、更个人化的实践空间':'知识结构与学习路径'}</p></div>`).join('')}</div></div><section id="analysis-0"><h2>1. 先看它在做什么</h2>${cards([['book','知识型内容平台','围绕主题组织概念与实践内容。'],['search','站内搜索','让用户从问题快速找到相关内容。'],['tree','结构化学习体系','用专题、系列与路径组织学习。']])}</section><section id="analysis-1"><h2>2. 最值得借鉴的地方</h2>${cards([['search','搜索优先','围绕问题组织入口。'],['layers','内容分层','从概念到实践，层次清晰。'],['tree','章节式学习','把内容串联为可回看的路径。']])}</section><section id="analysis-2"><h2>3. 不适合直接照搬的地方</h2><div class="ds-caution">${cards([['cube','内容太重','需要考虑个人维护成本。'],['grid','过于复杂','功能范围要匹配实际内容量。'],['book','个人感不足','保留自己的视角和具体实践。']])}</div></section><section id="analysis-3"><h2>4. 我会怎么用到自己的网站里</h2>${cards([['file','术语 → 知识','将零散解释整理成知识条目。'],['tree','学习路线 → 系列','组织自己的主题实践路径。'],['refresh','更新 → 最近变化','记录网站与内容的持续演进。']])}</section><section class="cl-card ds-take"><h2>5. 最后结论</h2><p>借鉴组织思路，结合自己的定位与维护能力，建立更轻量、更有个人特色的知识实践空间。</p></section></div><aside class="ds-series-aside"><div class="cl-card"><h2>拆解维度</h2>${['内容结构','导航','学习路径','个人化'].map((t,i)=>`<a class="ds-related-link" href="#/notes/${x.id}" data-ds-scroll="analysis-${Math.min(i,3)}">${icon(['file','grid','tree','book'][i])}<strong>${t}</strong><span>→</span></a>`).join('')}</div><div class="cl-card"><h2>相关页面</h2><a class="ds-related-link" href="#/learning?kind=CONCEPT">知识 →</a><a class="ds-related-link" href="#/learning?kind=NOTE">思考 →</a><a class="ds-related-link" href="#/projects">项目 →</a></div><blockquote class="cl-card">好的产品是激发思考的起点。</blockquote></aside></div>${columnTail}</article>`;}
function comparison(x){const rows=[['内容密度','高 · 适合深度阅读','中 · 以项目为主','高 · 包含过程笔记'],['导航清晰度','中 · 分类较多','高 · 直达项目','中 · 需要学习路径'],['个人表达','中 · 侧重知识','高 · 展现风格与能力','高 · 展现思考与成长'],['可扩展性','高 · 持续输出','中 · 随项目增长','高 · 记录与迭代'],['作品展示力','中 · 体现知识深度','高 · 直接展示作品','中 · 需结合项目']];return `<article class="cl-page ds-analysis site-container"><div class="ds-analysis-layout"><div>${heading(x)}<section><h2>对比对象</h2>${cards([['book','纯知识站','以知识输出为核心'],['cube','个人作品集','以项目展示为核心'],['layers','个人学习系统','以学习过程为核心']])}</section><section><h2>我重点比较什么</h2>${cards([['file','内容密度','页面的信息量'],['search','导航清晰度','是否容易找到内容'],['book','个人表达','能否体现自己的思考']])}</section><section><h2>简要对比</h2><div class="cl-card ds-table"><table><thead><tr>${['对比维度','纯知识站','个人作品集','个人学习系统'].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((t,i)=>`<${i?'td':'th'}>${t}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="cl-card ds-take"><h2>我的选择</h2><h3>个人作品集 + 知识系统</h3><p>以项目连接知识与思考，展示具体实践，也保留学习过程。根据内容规模逐步扩展。</p></section></div><aside class="ds-series-aside"><section class="cl-card"><h2>结论摘要</h2><div class="ds-take"><h3>个人作品集 + 知识系统</h3><p>纯知识适合积累内容，作品集便于直接展示实践。两者结合，让项目有方法依据，也让知识有实际应用场景。</p><p>有取舍地呈现真正重要的东西。</p></div></section><section class="cl-card"><h2>相关文章</h2>${articleLinks()}</section></aside></div>${columnTail}</article>`;}
export function mountDetailScroll(root){root.querySelectorAll('[data-ds-scroll]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const target=root.querySelector('#'+a.dataset.dsScroll);target?.scrollIntoView({behavior:globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});target?.setAttribute('tabindex','-1');target?.focus({preventScroll:true});}));}
