export const workItems = [
  // 1. Projects (完整项目)
  {
    id: 'ai-seven-dimension-eval',
    kind: 'PROJECT',
    kindLabel: '完整项目',
    badgeClass: 'badge-project',
    title: '七维能力自动评测系统',
    english: 'Seven-Dimension AI Auto-Evaluation System',
    status: 'IN PROGRESS',
    statusLabel: '进行中',
    role: '评测架构设计 / 规则引擎与 Judge 流水分层实现',
    time: '2026.08',
    domain: 'AI Evaluation & Agent Quality',
    summary: '针对 Agent 多轮交互与任务执行质量，构建规则引擎与 LLM Judge 分层的七维自动化能力评测与回归框架。',
    problem: '业务 Agent 复杂度上升后，人工抽检评测存在吞吐低（单次耗时数天）、标准主观漂移、且 Prompt 微调后无法自动化防退化回归的问题。',
    solution: '构建输入轨迹 (JSON Trace) → 确定性规则过滤层 (Rule Engine) → 七维原子化二元判定层 (LLM Judge) → 归一化聚合与 Diff 看板。',
    keyDecisions: [
      '确定性指标（字段存在性、状态跳转、超时、特定关键词）由代码规则引擎计算，不交给大模型。',
      '语义理解指标（回复同理心、意图理解、追问合理性）拆分为单一职责 Prompt，由 LLM Judge 进行 0-1 二元判定。',
      '引入 Few-Shot 标准样例对齐 Anchor 与 CoT 证据先行，消除不同批次打分漂移。'
    ],
    challenge: '大模型打分容易受回复长度、语气礼貌程度干扰，出现“长回复高分”或“自相矛盾打分”。通过字段级拆分与强制结构化理由先行（CoT + JSON Schema）彻底解决。',
    result: '自动化评测覆盖率从 0% 提升至 100%，单次全量评测耗时由 3 天人工缩短至 12 分钟，评测与专家人工对齐一致性达到 94.2%。',
    highlights: [
      { value: '3 天 → 12 分钟', label: '单次全量评测耗时' },
      { value: '94.2%', label: '与专家判断一致性' },
      { value: '100%', label: '自动化评测覆盖率' }
    ],
    whatILearned: '确定性问题规则化，非确定性语义问题模型化；永远不要让大模型去算代码即可 100% 确定计算的东西。',
    relatedTopics: ['testing-strategy', 'acceptance-criteria', 'system-prompt'],
    relatedNotes: ['note-eval-rules-vs-judge', 'note-accuracy-metric-fallacy'],
    relatedTools: ['tool-ai-eval-rule-design', 'tool-ai-launch-checklist']
  },
  {
    id: 'personal-knowledge-lab',
    kind: 'PROJECT',
    kindLabel: '完整项目',
    badgeClass: 'badge-project',
    title: 'Personal Knowledge Lab V2.0 / V3.0',
    english: 'Personal Knowledge Lab & AI Content Engine',
    status: 'IN PROGRESS',
    statusLabel: '迭代中',
    screenshot: './assets/work/personal-knowledge-lab.png',
    role: '全栈架构 / 内容引擎算法 / 交互设计 / 知识体系梳理',
    time: '2026.08',
    domain: 'Knowledge Engineering & Tooling',
    summary: '以真实项目与持续学习为输入，通过 AI Content Compiler 提炼关键节点，驱动知识、深度思考、复用方法与项目案例生成的个人知识实验室。',
    problem: '传统个人博客或知识库维护成本过高，容易陷入“为了写文章而写文章”的脱节状态；需要让日常做项目的过程自然沉淀为高质量知识资产。',
    solution: '解耦“内容生产系统”与“内容展示系统”，确立 DO → CAPTURE → AI DISTILL → REVIEW → PUBLISH 的极简沉淀闭环。',
    keyDecisions: [
      '日常只维护单一极简输入框，AI 固定提炼 6 个核心字段，不让用户填写繁琐表单。',
      'AI 提炼结果默认“仅保存”，生成公开草稿需经人工把关，避免 AI 制造无价值垃圾内容。',
      '知识库与项目实践双向打通，每个研究与 Playbook 都有真实项目证据支撑。'
    ],
    challenge: '设计 AI Compiler 的压缩提炼算法，确保输出具备事实密度与可验证性，坚决剔除流水账与空洞客套。',
    result: '建立完整的个人知识资产流水线，每次记录从原本 30 分钟写长文缩短至 30 秒随手记录，知识提炼效率提升 10 倍以上。',
    highlights: [
      { value: '30 分钟 → 30 秒', label: '单次记录输入时间' },
      { value: '10×', label: '知识提炼效率' },
      { value: 'DO → PUBLISH', label: '端到端沉淀闭环' }
    ],
    whatILearned: '做事情才是主干，整理知识是流水线自动化辅助；好系统不是让用户做更多输入，而是用确定性契约帮用户把无序材料编译成高信息密度的结构。',
    relatedTopics: ['component-thinking', 'state-management', 'api-contract'],
    relatedNotes: ['note-vibe-coding-mental-model', 'note-why-chat-ui-trap'],
    relatedTools: ['tool-prompt-debugging-workflow']
  },
  {
    id: 'wepictool-ai-image',
    kind: 'PROJECT',
    kindLabel: '完整项目',
    badgeClass: 'badge-project',
    title: 'AI 图片设计与出图小程序',
    english: 'AI Image Synthesis & Miniprogram',
    status: 'COMPLETED',
    statusLabel: '已上线',
    screenshot: './assets/work/wepictool-ai-image.png',
    role: '全栈开发 / 微信小程序 / 云开发托管 / 异步轮询任务流设计',
    time: '2026.06',
    domain: 'Fullstack & Generative AI',
    summary: '基于微信小程序与云开发托管的高性能轻量图片合成与个性化服饰换装工作流。',
    problem: '移动端用户希望在小程序内快速生成个性化图片，但大图生成耗时长（10~25s）易导致请求超时、多图层混合边缘锯齿以及云函数冷启动高延迟。',
    solution: '小程序前端交互画布 + 异步任务状态机轮询 + Docker 云托管 Node.js 渲染集群 + 图像大模型 API + CDN 缓存加速。',
    keyDecisions: [
      '长耗时任务采用异步轮询机制，前端提交后获取 Task ID，结合静默进度动画与状态机轮询。',
      '图像预处理与抠图分层在服务端进行，小程序仅负责画布合成与交互预览。'
    ],
    challenge: '网络弱网环境下轮询请求失败重试与任务状态幂等性保障。',
    result: '小程序月活突破 10,000+，图像生成成功率达到 99.6%，平均端到端出图耗时降低 45%。',
    highlights: [
      { value: '10,000+', label: '小程序月活' },
      { value: '99.6%', label: '图像生成成功率' },
      { value: '-45%', label: '平均端到端耗时' }
    ],
    whatILearned: '移动端 AI 产品体验的关键不是算法本身，而是针对慢速异步响应做极佳的状态管理与反馈设计。',
    relatedTopics: ['api-contract', 'state-management', 'error-handling'],
    relatedNotes: ['note-why-chat-ui-trap'],
    relatedTools: ['tool-ai-prd-template']
  },

  // 2. Prototypes (快速原型)
  {
    id: 'proto-local-rag-sandbox',
    kind: 'PROTOTYPE',
    kindLabel: '快速原型',
    badgeClass: 'badge-proto',
    title: '轻量级端侧 RAG 检索与上下文拼接原型',
    english: 'Lightweight Client-Side RAG Sandbox',
    status: 'COMPLETED',
    statusLabel: '已验证',
    time: '2026.07',
    domain: 'RAG & Vector Retrieval',
    summary: '在纯浏览器端基于 TF-IDF 与简易余弦相似度实现的完全离线文档分块、向量化与上下文动态注入 Demo。',
    problem: '验证小规模领域文档（100KB 内）在纯前端离线环境下进行实时召回与 Prompt 拼接的可行性与最优分块大小。',
    solution: '纯浏览器运行：分词器 → 滑动窗口切分 (Chunk 150 tokens, Overlap 30) → 向量余弦比对 → Top-3 注入 System Prompt。',
    result: '在小数据集上，带重叠窗口的滑动切分召回率比硬换行切分提高 32%，能有效解决关键上下文被切断的问题。',
    whatILearned: 'RAG 的质量首先取决于 Chunking 边界的合理性，而非单纯追求更复杂的向量数据库。',
    relatedTopics: ['rag', 'context-window', 'token'],
    relatedNotes: ['note-why-chat-ui-trap'],
    relatedTools: []
  },
  {
    id: 'proto-mcp-tool-client',
    kind: 'PROTOTYPE',
    kindLabel: '快速原型',
    badgeClass: 'badge-proto',
    title: 'MCP Server 与本地 Agent 工具调用沙盒',
    english: 'MCP Protocol Server & Tool Calling Sandbox',
    status: 'COMPLETED',
    statusLabel: '已验证',
    time: '2026.08',
    domain: 'Agent Protocols & MCP',
    summary: '基于标准 Model Context Protocol 构建的本地 SQLite 查询与系统状态读取客户端沙盒。',
    problem: '探索大模型如何通过自描述协议自主发现工具、校验入参并解析执行结果，验证多工具混排调用。',
    solution: 'Node.js MCP Server (暴露 list_tools / call_tool) + JSON-RPC 通信协议 + LLM Tool Calling Handler。',
    result: 'MCP 的 Schema 自描述机制让 Agent 接入新工具的适配代码量减少 80% 以上。',
    whatILearned: '标准协议消除了每个 AI 应用重复为模型编写适配中间件的繁琐成本。',
    relatedTopics: ['tool-calling', 'system-prompt', 'api-contract'],
    relatedNotes: ['note-mcp-vs-rest-api'],
    relatedTools: []
  },

  // 3. Experiments (实验验证)
  {
    id: 'exp-fewshot-judge-stability',
    kind: 'EXPERIMENT',
    kindLabel: '实验验证',
    badgeClass: 'badge-exp',
    title: 'Few-Shot 数量对 LLM Judge 评分一致性的影响实验',
    english: 'Impact of Few-Shot Examples on LLM Judge Stability',
    status: 'COMPLETED',
    statusLabel: '已结题',
    time: '2026.08',
    domain: 'AI Evaluation & Benchmarking',
    summary: '在 100 组具有争议的线上真实对话轨迹上，对比 0-Shot、1-Shot、3-Shot 与思维链 CoT 对模型打分方差的影响。',
    problem: '探究消除 LLM Judge 打分漂移的最经济 Prompt 构造方式。',
    solution: '测试集 100 条样本，每组重复运行 5 次计算方差与人工标注对齐度 (Cohen Kappa 指数)。',
    result: '3-Shot（含 1 个正例、1 个边缘 Case、1 个负例反思）配合理由先行 CoT，将打分方差从 0.84 骤降至 0.09，一致性与人工专家吻合度达到 93.8%。',
    whatILearned: '负样本 Few-Shot 的对齐价值远大于提供 10 个普通的正向示例。',
    relatedTopics: ['testing-strategy', 'acceptance-criteria', 'system-prompt'],
    relatedNotes: ['note-eval-rules-vs-judge', 'note-accuracy-metric-fallacy'],
    relatedTools: ['tool-ai-eval-rule-design']
  },
  {
    id: 'exp-json-schema-enforcement',
    kind: 'EXPERIMENT',
    kindLabel: '实验验证',
    badgeClass: 'badge-exp',
    title: '不同 Prompt 约束方式对 JSON Schema 严格遵循率的压测实验',
    english: 'Benchmark of JSON Output Enforcement Strategies',
    status: 'COMPLETED',
    statusLabel: '已结题',
    time: '2026.07',
    domain: 'Prompt Engineering & Reliability',
    summary: '在 200 次长文本抽取任务中，对比纯自然语言指令、Markdown 代码块标记、JSON Schema 约束与理由先行四种方案的解析失败率。',
    problem: '寻找在各类开源与闭源模型上保证结构化数据 100% 可解析的最佳实践。',
    solution: '模型包含 GPT-4o-mini, Claude-3.5-Haiku, Qwen-2.5-7B；统计 `JSON.parse` 抛错率与缺失必填字段率。',
    result: '仅依靠自然语言指令时解析报错率为 14.5%；引入“理由先行字段 (reasoning) + 明确 Schema”后，报错率降至 0.5% 以下。',
    whatILearned: '给模型一个先输出思考的 reasoning 字段，能极大缓解生成紧凑 JSON 时的注意力过载与格式崩溃。',
    relatedTopics: ['api-contract', 'system-prompt', 'error-handling'],
    relatedNotes: ['note-vibe-coding-mental-model'],
    relatedTools: ['tool-prompt-debugging-workflow']
  }
];
